import { NextRequest, NextResponse } from 'next/server'

interface Strength{point:string;detail:string}
interface Concern{title:string;whyCheck:string;howToResolve:string;resolvedWhen:string;cost:string}
interface ActionItem{title:string;priority:string;why:string;whatItUnlocks:string;nextStep:string;timing:string}
interface Avoidance{action:string;why:string}
interface SeasonalItem{action:string;why:string;timing:string}
interface ProgramScreen{name:string;why:string;value:string;caveat:string;url?:string}
interface ProjectIdea{title:string;scope:'big'|'small';cost:string;impact:string;dependencies:string;timing:string}
interface DataLink{label:string;url:string;what:string}
interface SnapshotFact{label:string;value:string}
interface Report{summary:string;snapshot:{address:string;town:string;county:string;facts:SnapshotFact[]};strengths:Strength[];concerns:Concern[];actions:ActionItem[];projects:ProjectIdea[];avoidances:Avoidance[];seasonal:SeasonalItem[];reasoning:string;programs:ProgramScreen[];dataLinks:DataLink[];generatedAt:string}

const TC: Record<string,string> = {
  'addison':'Addison','bridport':'Addison','bristol':'Addison','cornwall':'Addison','ferrisburgh':'Addison','goshen':'Addison','granville':'Addison','hancock':'Addison','leicester':'Addison','lincoln':'Addison','middlebury':'Addison','monkton':'Addison','new haven':'Addison','orwell':'Addison','panton':'Addison','ripton':'Addison','salisbury':'Addison','shoreham':'Addison','starksboro':'Addison','vergennes':'Addison','waltham':'Addison','weybridge':'Addison','whiting':'Addison',
  'arlington':'Bennington','bennington':'Bennington','dorset':'Bennington','glastenbury':'Bennington','landgrove':'Bennington','manchester':'Bennington','peru':'Bennington','pownal':'Bennington','readsboro':'Bennington','rupert':'Bennington','sandgate':'Bennington','searsburg':'Bennington','shaftsbury':'Bennington','stamford':'Bennington','sunderland':'Bennington','winhall':'Bennington','woodford':'Bennington',
  'barnet':'Caledonia','burke':'Caledonia','danville':'Caledonia','groton':'Caledonia','hardwick':'Caledonia','kirby':'Caledonia','lyndon':'Caledonia','lyndonville':'Caledonia','newark':'Caledonia','peacham':'Caledonia','ryegate':'Caledonia','sheffield':'Caledonia','st. johnsbury':'Caledonia','saint johnsbury':'Caledonia','st johnsbury':'Caledonia','stannard':'Caledonia','sutton':'Caledonia','walden':'Caledonia','waterford':'Caledonia','wheelock':'Caledonia',
  'bolton':'Chittenden','burlington':'Chittenden','charlotte':'Chittenden','colchester':'Chittenden','essex':'Chittenden','essex junction':'Chittenden','hinesburg':'Chittenden','huntington':'Chittenden','jericho':'Chittenden','milton':'Chittenden','richmond':'Chittenden','shelburne':'Chittenden','south burlington':'Chittenden','st. george':'Chittenden','underhill':'Chittenden','westford':'Chittenden','williston':'Chittenden','winooski':'Chittenden',
  'averill':'Essex','bloomfield':'Essex','brighton':'Essex','brunswick':'Essex','canaan':'Essex','concord':'Essex','east haven':'Essex','granby':'Essex','guildhall':'Essex','island pond':'Essex','lemington':'Essex','lunenburg':'Essex','maidstone':'Essex','norton':'Essex','victory':'Essex',
  'bakersfield':'Franklin','berkshire':'Franklin','enosburg':'Franklin','enosburg falls':'Franklin','fairfax':'Franklin','fairfield':'Franklin','fletcher':'Franklin','franklin':'Franklin','georgia':'Franklin','highgate':'Franklin','montgomery':'Franklin','richford':'Franklin','sheldon':'Franklin','st. albans':'Franklin','saint albans':'Franklin','st albans':'Franklin','swanton':'Franklin',
  'cabot':'Washington','calais':'Washington','duxbury':'Washington','east montpelier':'Washington','fayston':'Washington','marshfield':'Washington','middlesex':'Washington','montpelier':'Washington','moretown':'Washington','northfield':'Washington','plainfield':'Washington','roxbury':'Washington','waitsfield':'Washington','warren':'Washington','washington':'Washington','waterbury':'Washington','woodbury':'Washington','worcester':'Washington','barre':'Washington','berlin':'Washington',
  'belvidere':'Lamoille','cambridge':'Lamoille','eden':'Lamoille','elmore':'Lamoille','hyde park':'Lamoille','johnson':'Lamoille','morristown':'Lamoille','morrisville':'Lamoille','stowe':'Lamoille','waterville':'Lamoille','wolcott':'Lamoille',
  'barnard':'Windsor','bethel':'Windsor','bridgewater':'Windsor','cavendish':'Windsor','chester':'Windsor','hartford':'Windsor','hartland':'Windsor','ludlow':'Windsor','norwich':'Windsor','plymouth':'Windsor','pomfret':'Windsor','reading':'Windsor','rochester':'Windsor','royalton':'Windsor','sharon':'Windsor','springfield':'Windsor','stockbridge':'Windsor','weathersfield':'Windsor','west windsor':'Windsor','weston':'Windsor','windsor':'Windsor','woodstock':'Windsor','white river junction':'Windsor','quechee':'Windsor',
  'athens':'Windham','brattleboro':'Windham','brookline':'Windham','dover':'Windham','dummerston':'Windham','grafton':'Windham','guilford':'Windham','halifax':'Windham','jamaica':'Windham','londonderry':'Windham','marlboro':'Windham','newfane':'Windham','putney':'Windham','rockingham':'Windham','somerset':'Windham','stratton':'Windham','townshend':'Windham','vernon':'Windham','wardsboro':'Windham','west dover':'Windham','westminster':'Windham','whitingham':'Windham','wilmington':'Windham','windham':'Windham','bellows falls':'Windham','saxtons river':'Windham',
  'albany':'Orleans','barton':'Orleans','brownington':'Orleans','charleston':'Orleans','coventry':'Orleans','craftsbury':'Orleans','derby':'Orleans','glover':'Orleans','greensboro':'Orleans','holland':'Orleans','irasburg':'Orleans','jay':'Orleans','lowell':'Orleans','morgan':'Orleans','newport':'Orleans','troy':'Orleans','westfield':'Orleans','westmore':'Orleans',
  'brandon':'Rutland','castleton':'Rutland','chittenden':'Rutland','clarendon':'Rutland','danby':'Rutland','fair haven':'Rutland','hubbardton':'Rutland','ira':'Rutland','killington':'Rutland','mendon':'Rutland','middletown springs':'Rutland','mount holly':'Rutland','mount tabor':'Rutland','pawlet':'Rutland','pittsfield':'Rutland','pittsford':'Rutland','poultney':'Rutland','proctor':'Rutland','rutland':'Rutland','sherburne':'Rutland','shrewsbury':'Rutland','sudbury':'Rutland','tinmouth':'Rutland','wallingford':'Rutland','wells':'Rutland','west rutland':'Rutland',
  'bradford':'Orange','braintree':'Orange','brookfield':'Orange','chelsea':'Orange','corinth':'Orange','fairlee':'Orange','newbury':'Orange','orange':'Orange','randolph':'Orange','strafford':'Orange','thetford':'Orange','topsham':'Orange','tunbridge':'Orange','vershire':'Orange','west fairlee':'Orange','williamstown':'Orange',
  'alburgh':'Grand Isle','grand isle':'Grand Isle','isle la motte':'Grand Isle','north hero':'Grand Isle','south hero':'Grand Isle',
}
const LAKE_TOWNS: Record<string,string> = {'charlotte':'Lake Champlain','shelburne':'Lake Champlain','burlington':'Lake Champlain','colchester':'Lake Champlain','south hero':'Lake Champlain','north hero':'Lake Champlain','grand isle':'Lake Champlain','alburgh':'Lake Champlain','isle la motte':'Lake Champlain','st. albans':'Lake Champlain','swanton':'Lake Champlain','georgia':'Lake Champlain','milton':'Lake Champlain','greensboro':'Caspian Lake','craftsbury':'Great Hosmer Pond','barton':'Crystal Lake','glover':'Shadow Lake','westmore':'Lake Willoughby','morgan':'Seymour Lake','derby':'Lake Memphremagog','charleston':'Island Pond','castleton':'Lake Bomoseen','hubbardton':'Lake Hortonia','wilmington':'Harriman Reservoir','whitingham':'Harriman Reservoir','barnard':'Silver Lake','ludlow':'Lake Rescue','groton':'Lake Groton','peacham':'Peacham Pond','danville':'Joes Pond','calais':'Mirror Lake','woodbury':'multiple lakes','elmore':'Lake Elmore','eden':'Lake Eden'}
const ZONED = new Set(['burlington','south burlington','essex','colchester','williston','shelburne','charlotte','hinesburg','richmond','stowe','waterbury','montpelier','barre','middlebury','vergennes','bennington','brattleboro','rutland','st. albans','newport','hartford','norwich','woodstock','manchester','wilmington','dover','killington','ludlow','springfield','st. johnsbury','lyndon','morristown','johnson','waitsfield','warren','fayston'])
const RESORT = new Set(['stowe','killington','manchester','wilmington','dover','west dover','ludlow','waitsfield','warren','jay','burke','stratton','peru','winhall','landgrove'])
const ALL_TOWNS = Object.keys(TC)
const UTILITY: Record<string,string> = {};['burlington','south burlington','essex','colchester','williston','shelburne','charlotte','hinesburg','richmond','stowe','waterbury','montpelier','barre','middlebury','vergennes','bennington','brattleboro','rutland','newport','hartford','norwich','woodstock','manchester','wilmington','killington','ludlow','springfield','st. johnsbury','lyndon','morristown','johnson','cambridge','jericho','milton','underhill','westford','winooski','bolton','huntington','duxbury','fayston','waitsfield','warren','moretown','northfield','plainfield','marshfield','cabot','danville','barnet','groton','peacham','ryegate','newbury','bradford','corinth','thetford','fairlee','chelsea','randolph','bethel','rochester','pittsfield','stockbridge','barnard','pomfret','hartland','windsor','reading','cavendish','chester','grafton','newfane','townshend','jamaica','londonderry','weston','dorset','arlington','sunderland','rupert','pawlet','danby','wallingford','tinmouth','clarendon','pittsford','brandon','castleton','poultney','wells','middletown springs','shrewsbury','mount holly','plymouth'].forEach(t=>UTILITY[t]='Green Mountain Power');['albany','barton','brownington','charleston','coventry','craftsbury','derby','glover','greensboro','holland','irasburg','jay','lowell','morgan','troy','westfield','westmore','eden','belvidere','waterville','wolcott','elmore','hyde park','hardwick','walden','wheelock','stannard','sheffield','burke','kirby','lyndonville','sutton','newark','brighton','concord','east haven','granby','guildhall','lemington','lunenburg','maidstone','norton','victory','canaan','averill'].forEach(t=>{if(!UTILITY[t])UTILITY[t]='Vermont Electric Coop'})
function fuzzyMatch(input:string):string|null{const l=input.toLowerCase().trim();if(TC[l])return l;const c=l.replace(/\s+(village|city|town|center|centre)$/i,'');if(TC[c])return c;for(const t of ALL_TOWNS){if(l.includes(t)&&t.length>3)return t}for(const t of ALL_TOWNS){if(t.startsWith(l)||l.startsWith(t))return t}return null}
interface Parsed{street:string;town:string;county:string;isWaterfront:boolean;isRural:boolean;lakeName?:string;hasZoning:boolean;isResort:boolean;utility:string;townKey:string}
function parse(raw:string):{ok:boolean;parsed?:Parsed;error?:string;suggestion?:string}{
  let cleaned=raw.trim().replace(/\s+/g,' ').replace(/\b\d{5}(-\d{4})?\b/g,'').trim();if(cleaned.length<3)return{ok:false,error:'Address is too short.',suggestion:'Try: 142 Lakeshore Drive, Greensboro, VT'}
  const ws=cleaned.replace(/,?\s*(VT|Vermont|V\.T\.)\s*$/i,'').trim();const hasState=ws!==cleaned;const parts=ws.split(',').map(s=>s.trim()).filter(Boolean);let street='',townRaw=''
  if(parts.length>=2){street=parts[0];townRaw=parts[1]}else{const words=parts[0]?.split(' ')||[];let found:string|null=null;for(let i=words.length-1;i>=1;i--){const m=fuzzyMatch(words.slice(i).join(' '));if(m){found=m;street=words.slice(0,i).join(' ');break}}if(!found)for(let i=words.length-2;i>=1;i--){const m=fuzzyMatch(words.slice(i,i+2).join(' '));if(m){found=m;street=words.slice(0,i).join(' ');break}}if(found)townRaw=found;else if(!hasState)return{ok:false,error:`Could not identify a Vermont town in "${raw}".`,suggestion:'Add comma and town: 123 Main St, Stowe, VT'};else{street=parts[0]||'';townRaw=''}}
  const matched=fuzzyMatch(townRaw);if(matched){const proper=matched.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ').replace(/^St\. /i,'St. ');const lf=raw.toLowerCase();const isWF=['lake','shore','pond','river','beach','cove','bay','point','landing','harbor','marina','waterfront','island'].some(s=>lf.includes(s))||!!LAKE_TOWNS[matched];const isR=['route ','rt ','mountain','hill','hollow','ridge','kingdom','lot ','class 4','dirt road','gravel'].some(s=>lf.includes(s));return{ok:true,parsed:{street:street||raw.split(',')[0]?.trim()||raw,town:proper,county:TC[matched]||'Unknown',isWaterfront:isWF,isRural:isR,lakeName:LAKE_TOWNS[matched],hasZoning:ZONED.has(matched),isResort:RESORT.has(matched),utility:UTILITY[matched]||'Check with town',townKey:matched}}}
  if(townRaw){const close=ALL_TOWNS.filter(t=>t.includes(townRaw.toLowerCase().slice(0,4))||townRaw.toLowerCase().includes(t.slice(0,4))).slice(0,3);return{ok:false,error:`"${townRaw}" not recognized as a Vermont town.`,suggestion:close.length?`Did you mean: ${close.map(t=>t.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ')).join(', ')}?`:'Example: 123 Main St, Stowe, VT'}}
  return{ok:false,error:`Could not identify a town in "${raw}".`,suggestion:'Include a Vermont town: 142 Lakeshore Drive, Greensboro, VT'}
}
function buildReport(p:Parsed):Report{
  const month=new Date().getMonth();const isWinter=month>=10||month<=3,isSummer=month>=5&&month<=8
  const strengths:Strength[]=[]
  if(p.isWaterfront)strengths.push({point:`Waterfront${p.lakeName?` — ${p.lakeName}`:''}`,detail:'Waterfront properties hold value well and have consistent buyer/renter demand in Vermont.'})
  if(p.isResort)strengths.push({point:`${p.town} destination market`,detail:'Resort towns support higher rental rates and a broader buyer pool than rural Vermont generally.'})
  strengths.push({point:`${p.county} County`,detail:`Vermont\'s seasonal market brand — clean water, outdoor access, four seasons — supports long-term property values in ${p.county} County.`})
  if(!p.isRural)strengths.push({point:'Year-round access',detail:'Town-maintained road access makes the property easier to use, insure, and sell.'})
  strengths.push({point:'Strong energy incentives',detail:`${p.utility} territory qualifies for Efficiency Vermont rebates. Heat pump and insulation upgrades can be offset 30–50%.`})
  let summary='';if(p.isWaterfront)summary=`A ${p.town} waterfront property${p.lakeName?` on ${p.lakeName}`:''} — strong location in Vermont\'s seasonal market. Priority: confirm the home\'s systems are solid before investing in improvements, and understand what shoreline rules allow before planning outdoor work.`;else if(p.isRural)summary=`Rural ${p.town} property with the privacy and land appeal that drives Vermont\'s seasonal market. Priority: confirm septic, well, and heating are sound before spending on anything visible.`;else summary=`Well-positioned ${p.town} property in ${p.county} County. Confirm core systems — septic, water, heat — then plan improvements with confidence.`
  const facts:SnapshotFact[]=[{label:'Town',value:p.town},{label:'County',value:p.county},{label:'Zoning',value:p.hasZoning?'Local zoning adopted':'Limited — Act 250 at 1 acre'},{label:'Utility',value:p.utility}]
  if(p.isWaterfront)facts.push({label:'Water',value:p.lakeName||'Waterfront indicated'});if(p.isResort)facts.push({label:'Market',value:'Resort/destination'})
  const concerns:Concern[]=[
    {title:'Septic system — is it in good shape?',whyCheck:'Most VT seasonal homes use septic. An old or undersized system limits bedrooms, blocks rentals, and costs $15,000–$40,000 to replace. A clean inspection means you\'re clear.',howToResolve:'Get it pumped and inspected by a licensed hauler. Request the original design permit from the VT DEC regional office — shows age and capacity.',resolvedWhen:'Recent inspection confirms function and capacity matches your plans.',cost:'$300–$500 inspection. Permit records are free.'},
    {title:'Well water — tested recently?',whyCheck:'Private wells are standard in rural VT. Vermont bedrock has naturally occurring arsenic in some areas. A clean test = done. Treatment if needed runs $2,000–$8,000.',howToResolve:'Order a test kit from a state-certified lab. Test for coliform, E. coli, arsenic, lead. Check flow rate — under 3 GPM is limiting.',resolvedWhen:'Clean test on file, adequate flow rate confirmed.',cost:'$100–$400. Results in 1–2 weeks.'},
    {title:'Heating — usable beyond summer?',whyCheck:'Many seasonal homes have minimal heat (woodstove, wall unit). Without adequate heating, pipes freeze, insurance is harder, and the property is summer-only. Upgrading opens rental income and 4-season use.',howToResolve:'Walk the property: what\'s the heat source? Where do water pipes run? If minimal, get a heat pump quote — VT rebates make it 30–50% cheaper.',resolvedWhen:'Heating keeps property above freezing when vacant, or plumbing is winterized.',cost:'Free to assess. Heat pump: $3,000–$12,000 after rebates.'},
  ]
  if(p.isWaterfront)concerns.push({title:`Shoreline rules — what\'s buildable near ${p.lakeName||'the water'}?`,whyCheck:'VT Shoreland Protection Act limits clearing, patios, and additions within 250 ft of water. Not a dealbreaker — but you need to know the boundaries before designing.',howToResolve:`Get a property survey showing the shoreland buffer. Call ${p.town} zoning office about setback requirements. Check ANR Atlas for mapped zones.`,resolvedWhen:'Survey shows setbacks; you know what needs a permit vs. what\'s allowed.',cost:'$500–$2,000 survey. Permit apps $50–$200.'})
  concerns.push({title:'Taxes — will improvements spike the bill?',whyCheck:`Seasonal homes pay VT\'s higher non-homestead education tax rate. If the property is under-assessed relative to market, major improvements can trigger reappraisal.`,howToResolve:`Pull the property record card from ${p.town} town clerk. Compare assessed value to recent comparable sales. Model tax impact before budgeting.`,resolvedWhen:'You know assessed vs. market value and have modeled the reappraisal risk.',cost:'Free — town records are public.'})

  const actions:ActionItem[]=[
    {title:'Get the septic inspected',priority:'First',why:'Gates everything else — renovations, rentals, resale.',whatItUnlocks:'Confidence to plan improvements, bedroom capacity clarity, clean sale path.',nextStep:'Call a licensed septic service and schedule pump-out with inspection.',timing:'Before any renovation planning.'},
    {title:'Test the well water',priority:'First',why:'Cheap, fast, resolves a major unknown.',whatItUnlocks:'Peace of mind, lender compliance, rental eligibility.',nextStep:'Search "Vermont certified water testing labs" and order a kit.',timing:'This month.'},
    {title:'Assess the heating situation',priority:'Before fall',why:'Determines 3-season vs. 4-season capability.',whatItUnlocks:'Winter use, rental income, freeze protection.',nextStep:'Note heat source, fuel type, and pipe locations. Get heat pump quote if needed.',timing:'Before October.'},
  ]
  if(p.isWaterfront)actions.splice(2,0,{title:'Check shoreline rules for your parcel',priority:'Before outdoor work',why:'Prevents wasted design costs and permit surprises.',whatItUnlocks:'Realistic scope for decks, docks, landscaping, additions.',nextStep:`Call ${p.town} zoning office about shoreland setbacks.`,timing:'Before hiring a contractor.'})
  actions.push({title:'Check property tax exposure',priority:'Before big budget',why:'Know your reassessment risk before committing capital.',whatItUnlocks:'Accurate renovation budgeting.',nextStep:`Look up your property on the ${p.town} town clerk site.`,timing:'Before a $25k+ renovation.'})

  const projects:ProjectIdea[]=[]
  projects.push({title:'Smart thermostat + leak sensors',scope:'small',cost:'$200–$500',impact:'Remote monitoring prevents freeze damage during vacant periods. Insurance companies increasingly offer discounts.',dependencies:'Requires Wi-Fi at property.',timing:'Before winter.'})
  projects.push({title:'Dehumidifier for basement/crawlspace',scope:'small',cost:'$300–$800',impact:'Reduces mold risk, musty smell, and structural moisture damage common in seasonal homes that sit closed up.',dependencies:'None — plug and go.',timing:'Anytime.'})
  projects.push({title:'Exterior storm window restoration',scope:'small',cost:'$100–$300/window',impact:'Improves thermal performance of original windows without replacing them. Preserves character, reduces drafts.',dependencies:'None. DIY-friendly.',timing:'Before heating season.'})
  projects.push({title:'Gutter guards + drainage extension',scope:'small',cost:'$500–$2,000',impact:'Prevents ice dams, foundation water, and basement flooding. Most cost-effective exterior maintenance upgrade.',dependencies:'Inspect roof condition first.',timing:'Before fall.'})
  if(p.isWaterfront)projects.push({title:'Shoreline buffer planting',scope:'small',cost:'$500–$2,000',impact:`Native plantings within the shoreland buffer improve ${p.lakeName||'lake'} water quality, reduce erosion, and satisfy Shoreland Protection Act requirements.`,dependencies:'Check shoreland permit requirements first.',timing:'Spring or early fall.'})
  projects.push({title:'Cold-climate heat pump system',scope:'big',cost:'$8,000–$20,000 before rebates; $3,000–$12,000 after',impact:'Converts property from 3-season to 4-season. Adds rental income potential. Dramatically reduces heating costs vs. propane/oil.',dependencies:'Electrical panel may need upgrade (100A → 200A). Septic and water should be confirmed first.',timing:'Spring or fall. Book 4–8 weeks ahead.'})
  projects.push({title:'Full insulation and air sealing',scope:'big',cost:'$5,000–$15,000 before rebates',impact:'Reduces heating costs 30–50%. Improves comfort. May be required before heat pump sizing.',dependencies:'Best done before or alongside heating upgrade. Efficiency Vermont offers energy audits.',timing:'Any season.'})
  if(p.isWaterfront)projects.push({title:'Dock rebuild or permitted dock installation',scope:'big',cost:'$5,000–$25,000',impact:`Functional dock access significantly impacts ${p.lakeName||'waterfront'} property value and usability.`,dependencies:'Requires shoreland permit from VT ANR. Survey showing setbacks needed first.',timing:'Winter planning, spring installation.'})
  projects.push({title:'ADU or guest cabin',scope:'big',cost:'$50,000–$150,000+',impact:'Adds rental income stream, guest capacity, or caretaker housing. VT passed ADU-friendly legislation in 2023.',dependencies:`Septic capacity is the gate — must support additional bedrooms. ${p.hasZoning?'Check '+p.town+' zoning for ADU setbacks.':'Act 250 review at 1 acre threshold.'}`,timing:'Plan in winter, permit in spring, build in summer.'})
  projects.push({title:'Solar array or community solar subscription',scope:'big',cost:'$15,000–$30,000 for on-site; $0 for community solar',impact:`Offsets electricity costs, especially if pairing with heat pumps. ${p.utility} net metering rates apply.`,dependencies:'Roof condition and orientation matter for on-site. Community solar has no site requirements.',timing:'Any season for community solar sign-up.'})

  const avoidances:Avoidance[]=[
    {action:'Kitchen/bath renovation before septic check',why:'Septic work tears through finished spaces. Check it first.'},
    {action:'Addition plans before permit research',why:`${p.isWaterfront?'Shoreline rules may block it. ':''}Plans that don\'t comply = wasted design fees.`},
    {action:'High-end finishes before systems are confirmed',why:'Systems first, finishes second. Reliability sells better than luxury in this market.'},
  ]

  const seasonal:SeasonalItem[]=[]
  if(isWinter){seasonal.push({action:'Confirm freeze protection',why:'Burst pipe while vacant = $10,000+ damage.',timing:'Check now, weekly through winter.'});seasonal.push({action:'Clear heavy snow from roof',why:'Older framing + snow load = risk.',timing:'After 12"+ storms.'});seasonal.push({action:'Book spring contractors now',why:'VT contractors book 2–4 months out.',timing:'Now.'})}
  else if(isSummer){seasonal.push({action:'Pump septic before peak guests',why:'Heavy use on unserviced system risks backups.',timing:'Before Memorial Day.'});seasonal.push({action:'Test well water',why:'Know before you drink it all summer.',timing:'This month.'});seasonal.push({action:`Check ${p.town} STR rules`,why:'Registration required in more VT towns.',timing:'Before listing.'})}
  else{seasonal.push({action:'Winterize before first freeze',why:'VT freezes as early as late Sept at elevation.',timing:'By mid-October.'});seasonal.push({action:'Book contractors for spring',why:'Wait = summer start dates.',timing:'Now.'});seasonal.push({action:'Check roof and gutters',why:'Damaged gutters → ice dams → water damage.',timing:'Before snow.'})}
  if(p.isWaterfront)seasonal.push({action:'Inspect dock and shoreline',why:'Unpermitted repairs in shoreland zone = fines.',timing:isSummer?'Start of season.':'Spring.'})

  let reasoning=`These recommendations reflect how Vermont seasonal properties actually work: invisible systems (septic, well, heating) determine capability and value. `
  if(p.isWaterfront)reasoning+=`Waterfront parcels${p.lakeName?` on ${p.lakeName}`:''} carry shoreline regulations worth understanding before designing improvements. `
  if(p.isResort)reasoning+=`${p.town}\'s resort market adds rental potential but also regulatory complexity. `
  reasoning+=`Projects are sequenced so each step confirms you\'re clear or catches a problem before it gets expensive.`

  const programs:ProgramScreen[]=[
    {name:'Efficiency Vermont Rebates',why:`${p.utility} customers qualify. Heat pump rebates $800–$2,000, insulation $200–$2,000.`,value:'$500–$4,000',caveat:'Requires specific equipment + participating contractors.',url:'https://www.efficiencyvermont.com/rebates'},
    {name:'Federal 25C Tax Credit',why:'30% credit for heat pumps ($2,000 cap) and insulation ($1,200 cap).',value:'Up to $3,200/year',caveat:'Some limits for second homes. Confirm with tax advisor.'},
    {name:'VT Weatherization',why:'Free for income-eligible. Market-rate available through EVT network.',value:'Free or $3,000–$8,000',caveat:'6–12 month wait for free program.'},
    {name:'Current Use (Use Value Appraisal)',why:'If parcel has 25+ acres of managed forest, land taxes drop 50–90%.',value:'Significant tax reduction on land',caveat:'Requires forest management plan. Land Use Change Tax if withdrawn.',url:'https://fpr.vermont.gov/forest/use-value-appraisal'},
  ]

  const dataLinks:DataLink[]=[
    {label:'VT Parcel Viewer',url:'https://experience.arcgis.com/experience/b5a5cc7663c84761a305f70b913e1a60',what:'Look up your parcel by address — shows assessed value, acreage, SPAN number, and owner info.'},
    {label:'VT Property Transfer Records',url:'https://www.vtrealestatevalues.com/',what:`Search sale history for ${p.town} properties going back to 1987.`},
    {label:'FEMA Flood Map',url:'https://msc.fema.gov/portal/home',what:'Enter your address to check flood zone status. Determines insurance requirements and improvement restrictions.'},
    {label:'ANR Natural Resources Atlas',url:'https://anrmaps.vermont.gov/websites/anra5/',what:`View shoreland zones, wetlands, river corridors, and environmental constraints for your ${p.town} parcel.`},
    {label:'Efficiency Vermont Rebates',url:'https://www.efficiencyvermont.com/rebates',what:'Check current rebates for heat pumps, insulation, water heaters, and appliances.'},
    {label:`${p.town} Town Records`,url:'https://www.vtrealestatevalues.com/',what:`Search ${p.town} grand list for assessed values, property cards, and tax information.`},
  ]

  return{summary,snapshot:{address:`${p.street}, ${p.town}, ${p.county} County, VT`,town:p.town,county:p.county,facts},strengths,concerns,actions,projects,avoidances,seasonal,reasoning,programs,dataLinks,generatedAt:new Date().toISOString()}
}
export async function POST(req:NextRequest){try{const{address}=await req.json();if(!address||address.trim().length<3)return NextResponse.json({error:'Please enter an address.',suggestion:'Example: 142 Lakeshore Drive, Greensboro, VT'},{status:400});const result=parse(address);if(!result.ok||!result.parsed)return NextResponse.json({error:result.error,suggestion:result.suggestion},{status:400});return NextResponse.json(buildReport(result.parsed))}catch{return NextResponse.json({error:'Analysis failed.'},{status:500})}}
