import { NextRequest, NextResponse } from 'next/server'

interface Strength { point: string; detail: string }
interface Concern { title: string; whyCheck: string; howToResolve: string; resolvedWhen: string; cost: string }
interface ActionItem { title: string; priority: string; why: string; whatItUnlocks: string; nextStep: string; timing: string }
interface Avoidance { action: string; why: string }
interface SeasonalItem { action: string; why: string; timing: string }
interface ProgramScreen { name: string; why: string; value: string; caveat: string; url?: string }
interface SnapshotFact { label: string; value: string }
interface Report { summary: string; snapshot: { address: string; town: string; county: string; facts: SnapshotFact[] }; strengths: Strength[]; concerns: Concern[]; actions: ActionItem[]; avoidances: Avoidance[]; seasonal: SeasonalItem[]; reasoning: string; programs: ProgramScreen[]; generatedAt: string }

const TC: Record<string,string> = {
  'addison':'Addison','bridport':'Addison','bristol':'Addison','cornwall':'Addison','ferrisburgh':'Addison','goshen':'Addison','granville':'Addison','hancock':'Addison','leicester':'Addison','lincoln':'Addison','middlebury':'Addison','monkton':'Addison','new haven':'Addison','orwell':'Addison','panton':'Addison','ripton':'Addison','salisbury':'Addison','shoreham':'Addison','starksboro':'Addison','vergennes':'Addison','waltham':'Addison','weybridge':'Addison','whiting':'Addison',
  'arlington':'Bennington','bennington':'Bennington','dorset':'Bennington','glastenbury':'Bennington','landgrove':'Bennington','manchester':'Bennington','peru':'Bennington','pownal':'Bennington','readsboro':'Bennington','rupert':'Bennington','sandgate':'Bennington','searsburg':'Bennington','shaftsbury':'Bennington','stamford':'Bennington','sunderland':'Bennington','winhall':'Bennington','woodford':'Bennington',
  'barnet':'Caledonia','burke':'Caledonia','danville':'Caledonia','groton':'Caledonia','hardwick':'Caledonia','kirby':'Caledonia','lyndon':'Caledonia','lyndonville':'Caledonia','newark':'Caledonia','peacham':'Caledonia','ryegate':'Caledonia','sheffield':'Caledonia','st. johnsbury':'Caledonia','saint johnsbury':'Caledonia','st johnsbury':'Caledonia','stannard':'Caledonia','sutton':'Caledonia','walden':'Caledonia','waterford':'Caledonia','wheelock':'Caledonia',
  'bolton':'Chittenden','burlington':'Chittenden','charlotte':'Chittenden','colchester':'Chittenden','essex':'Chittenden','essex junction':'Chittenden','hinesburg':'Chittenden','huntington':'Chittenden','jericho':'Chittenden','milton':'Chittenden','richmond':'Chittenden','shelburne':'Chittenden','south burlington':'Chittenden','st. george':'Chittenden','underhill':'Chittenden','westford':'Chittenden','williston':'Chittenden','winooski':'Chittenden',
  'averill':'Essex','bloomfield':'Essex','brighton':'Essex','brunswick':'Essex','canaan':'Essex','concord':'Essex','east haven':'Essex','granby':'Essex','guildhall':'Essex','island pond':'Essex','lemington':'Essex','lunenburg':'Essex','maidstone':'Essex','norton':'Essex','victory':'Essex',
  'bakersfield':'Franklin','berkshire':'Franklin','enosburg':'Franklin','enosburg falls':'Franklin','fairfax':'Franklin','fairfield':'Franklin','fletcher':'Franklin','franklin':'Franklin','georgia':'Franklin','highgate':'Franklin','montgomery':'Franklin','richford':'Franklin','sheldon':'Franklin','st. albans':'Franklin','saint albans':'Franklin','st albans':'Franklin','swanton':'Franklin',
  'cabot':'Washington','calais':'Washington','duxbury':'Washington','east montpelier':'Washington','fayston':'Washington','marshfield':'Washington','middlesex':'Washington','montpelier':'Washington','moretown':'Washington','northfield':'Washington','plainfield':'Washington','roxbury':'Washington','waitsfield':'Washington','warren':'Washington','washington':'Washington','waterbury':'Washington','woodbury':'Washington','worcester':'Washington','barre':'Washington','berlin':'Washington',
  'belvidere':'Lamoille','cambridge':'Lamoille','eden':'Lamoille','elmore':'Lamoille','hyde park':'Lamoille','johnson':'Lamoille','morristown':'Lamoille','morrisville':'Lamoille','stowe':'Lamoille','waterville':'Lamoille','wolcott':'Lamoille',
  'barnard':'Windsor','bethel':'Windsor','bridgewater':'Windsor','cavendish':'Windsor','chester':'Windsor','hartford':'Windsor','hartland':'Windsor','ludlow':'Windsor','norwich':'Windsor','plymouth':'Windsor','pomfret':'Windsor','reading':'Windsor','rochester':'Windsor','royalton':'Windsor','sharon':'Windsor','springfield':'Windsor','stockbridge':'Windsor','weathersfield':'Windsor','west windsor':'Windsor','weston':'Windsor','windsor':'Windsor','woodstock':'Windsor','white river junction':'Windsor','quechee':'Windsor',
  'athens':'Windham','brattleboro':'Windham','brookline':'Windham','dover':'Windham','dummerston':'Windham','grafton':'Windham','guilford':'Windham','halifax':'Windham','jamaica':'Windham','londonderry':'Windham','marlboro':'Windham','newfane':'Windham','putney':'Windham','rockingham':'Windham','somerset':'Windham','stratton':'Windham','townshend':'Windham','vernon':'Windham','wardsboro':'Windham','west dover':'Windham','westminster':'Windham','whitingham':'Windham','wilmington':'Windham','windham':'Windham','bellows falls':'Windham','saxtons river':'Windham',
  'albany':'Orleans','barton':'Orleans','brownington':'Orleans','charleston':'Orleans','coventry':'Orleans','craftsbury':'Orleans','derby':'Orleans','glover':'Orleans','greensboro':'Orleans','holland':'Orleans','irasburg':'Orleans','jay':'Orleans','lowell':'Orleans','morgan':'Orleans','newport':'Orleans','troy':'Orleans','westfield':'Orleans','westmore':'Orleans',
  'brandon':'Rutland','castleton':'Rutland','chittenden':'Rutland','clarendon':'Rutland','danby':'Rutland','fair haven':'Rutland','hubbardton':'Rutland','ira':'Rutland','killington':'Rutland','mendon':'Rutland','middletown springs':'Rutland','mount holly':'Rutland','mount tabor':'Rutland','pawlet':'Rutland','pittsfield':'Rutland','pittsford':'Rutland','poultney':'Rutland','proctor':'Rutland','rutland':'Rutland','sherburne':'Rutland','shrewsbury':'Rutland','sudbury':'Rutland','tinmouth':'Rutland','wallingford':'Rutland','wells':'Rutland','west rutland':'Rutland',
  'bradford':'Orange','braintree':'Orange','brookfield':'Orange','chelsea':'Orange','corinth':'Orange','fairlee':'Orange','newbury':'Orange','orange':'Orange','randolph':'Orange','strafford':'Orange','thetford':'Orange','topsham':'Orange','tunbridge':'Orange','vershire':'Orange','west fairlee':'Orange','williamstown':'Orange',
  'alburgh':'Grand Isle','grand isle':'Grand Isle','isle la motte':'Grand Isle','north hero':'Grand Isle','south hero':'Grand Isle',
}
const LAKE_TOWNS: Record<string,string> = {'charlotte':'Lake Champlain','shelburne':'Lake Champlain','burlington':'Lake Champlain','colchester':'Lake Champlain','south hero':'Lake Champlain','north hero':'Lake Champlain','grand isle':'Lake Champlain','alburgh':'Lake Champlain','isle la motte':'Lake Champlain','st. albans':'Lake Champlain','swanton':'Lake Champlain','georgia':'Lake Champlain','milton':'Lake Champlain','greensboro':'Caspian Lake','craftsbury':'Great Hosmer Pond','barton':'Crystal Lake','glover':'Shadow Lake','westmore':'Lake Willoughby','morgan':'Seymour Lake','derby':'Lake Memphremagog','charleston':'Island Pond','castleton':'Lake Bomoseen','hubbardton':'Lake Hortonia','wilmington':'Harriman Reservoir','whitingham':'Harriman Reservoir','barnard':'Silver Lake','ludlow':'Lake Rescue','groton':'Lake Groton','peacham':'Peacham Pond','danville':'Joes Pond','calais':'Mirror Lake','woodbury':'multiple lakes','elmore':'Lake Elmore','eden':'Lake Eden'}
const ZONED = new Set(['burlington','south burlington','essex','colchester','williston','shelburne','charlotte','hinesburg','richmond','stowe','waterbury','montpelier','barre','middlebury','vergennes','bennington','brattleboro','rutland','st. albans','newport','hartford','norwich','woodstock','manchester','wilmington','dover','killington','ludlow','springfield','st. johnsbury','lyndon','morristown','johnson','waitsfield','warren','fayston'])
const RESORT = new Set(['stowe','killington','manchester','wilmington','dover','west dover','ludlow','waitsfield','warren','jay','burke','stratton','peru','winhall','landgrove'])
const ALL_TOWNS = Object.keys(TC)
function fuzzyMatch(input:string):string|null{const l=input.toLowerCase().trim();if(TC[l])return l;const c=l.replace(/\s+(village|city|town|center|centre)$/i,'');if(TC[c])return c;for(const t of ALL_TOWNS){if(l.includes(t)&&t.length>3)return t}for(const t of ALL_TOWNS){if(t.startsWith(l)||l.startsWith(t))return t}return null}
interface Parsed{street:string;town:string;county:string;isWaterfront:boolean;isRural:boolean;lakeName?:string;hasZoning:boolean;isResort:boolean}
function parse(raw:string):{ok:boolean;parsed?:Parsed;error?:string;suggestion?:string}{let cleaned=raw.trim().replace(/\s+/g,' ').replace(/\b\d{5}(-\d{4})?\b/g,'').trim();if(cleaned.length<3)return{ok:false,error:'Address is too short.',suggestion:'Try: 142 Lakeshore Drive, Greensboro, VT'};const ws=cleaned.replace(/,?\s*(VT|Vermont|V\.T\.)\s*$/i,'').trim();const hasState=ws!==cleaned;const parts=ws.split(',').map(s=>s.trim()).filter(Boolean);let street='',townRaw='';if(parts.length>=2){street=parts[0];townRaw=parts[1]}else{const words=parts[0]?.split(' ')||[];let found:string|null=null;for(let i=words.length-1;i>=1;i--){const m=fuzzyMatch(words.slice(i).join(' '));if(m){found=m;street=words.slice(0,i).join(' ');break}}if(!found)for(let i=words.length-2;i>=1;i--){const m=fuzzyMatch(words.slice(i,i+2).join(' '));if(m){found=m;street=words.slice(0,i).join(' ');break}}if(found)townRaw=found;else if(!hasState)return{ok:false,error:`Could not identify a Vermont town in "${raw}".`,suggestion:'Add comma and town: 123 Main St, Stowe, VT'};else{street=parts[0]||'';townRaw=''}}const matched=fuzzyMatch(townRaw);if(matched){const proper=matched.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ').replace(/^St\. /i,'St. ');const lf=raw.toLowerCase();const isWF=['lake','shore','pond','river','beach','cove','bay','point','landing','harbor','marina','waterfront','island'].some(s=>lf.includes(s))||!!LAKE_TOWNS[matched];const isR=['route ','rt ','mountain','hill','hollow','ridge','kingdom','lot ','class 4','dirt road','gravel'].some(s=>lf.includes(s));return{ok:true,parsed:{street:street||raw.split(',')[0]?.trim()||raw,town:proper,county:TC[matched]||'Unknown',isWaterfront:isWF,isRural:isR,lakeName:LAKE_TOWNS[matched],hasZoning:ZONED.has(matched),isResort:RESORT.has(matched)}}}if(townRaw){const close=ALL_TOWNS.filter(t=>t.includes(townRaw.toLowerCase().slice(0,4))||townRaw.toLowerCase().includes(t.slice(0,4))).slice(0,3);return{ok:false,error:`"${townRaw}" not recognized as a Vermont town.`,suggestion:close.length?`Did you mean: ${close.map(t=>t.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ')).join(', ')}?`:'Example: 123 Main St, Stowe, VT'}}return{ok:false,error:`Could not identify a town in "${raw}".`,suggestion:'Include a Vermont town: 142 Lakeshore Drive, Greensboro, VT'}}

function buildReport(p:Parsed):Report{
  const month=new Date().getMonth();const isWinter=month>=10||month<=3,isSummer=month>=5&&month<=8
  const strengths:Strength[]=[]
  if(p.isWaterfront)strengths.push({point:`Waterfront location${p.lakeName?` on ${p.lakeName}`:''}`,detail:'Waterfront properties in Vermont hold value well and have consistent demand from buyers and renters. This is a durable asset.'})
  if(p.isResort)strengths.push({point:`${p.town} is a recognized destination market`,detail:'Resort towns support higher rental rates and have a broader buyer pool than rural Vermont generally.'})
  strengths.push({point:`${p.county} County location`,detail:`Properties in ${p.county} County benefit from Vermont\'s strong seasonal market. The state\'s brand — clean water, outdoor access, four-season landscape — supports long-term property values.`})
  if(!p.isRural)strengths.push({point:'Accessible location',detail:'Properties with town-maintained road access are easier to use year-round, easier to insure, and more attractive to buyers.'})
  strengths.push({point:'Vermont energy incentives are strong',detail:'Vermont has some of the best energy upgrade incentives in the country. If this property needs heating or insulation improvements, rebates can offset 30–50% of the cost.'})

  let summary=''
  if(p.isWaterfront)summary=`This is a ${p.town} waterfront property${p.lakeName?` on ${p.lakeName}`:''} — a strong location in Vermont\'s seasonal market. To get the most out of it, the priority is making sure the home\'s systems (septic, well, heating) are in good shape before investing in renovations. For waterfront properties, it\'s also worth checking what shoreline rules allow before planning any outdoor work.`
  else if(p.isRural)summary=`This ${p.town} property has the appeal of rural Vermont — privacy, land, and access to the outdoors. The key to protecting that investment is making sure the basics are solid: septic system, well water, and heating. Getting those confirmed early saves money and prevents surprises.`
  else summary=`This ${p.town} property is well-positioned in ${p.county} County\'s seasonal market. The smartest first move is confirming the home\'s core systems are working — septic, water, heat. Once those check out, you can plan improvements with confidence.`

  const facts:SnapshotFact[]=[{label:'Town',value:p.town},{label:'County',value:p.county},{label:'Zoning',value:p.hasZoning?'Town has local zoning':'Limited local zoning'}]
  if(p.isWaterfront)facts.push({label:'Water body',value:p.lakeName||'Waterfront indicated'})
  if(p.isResort)facts.push({label:'Market type',value:'Resort / destination town'})

  const concerns:Concern[]=[
    {title:'Septic system — is it in good shape?',whyCheck:'Most Vermont seasonal homes have a septic system instead of town sewer. If it\'s old or undersized, it can limit what you do with the property — from adding a bathroom to renting it out. A system in good shape is a non-issue. One that needs replacing runs $15,000–$40,000.',howToResolve:'Call a licensed septic hauler and get it pumped and inspected. Ask them to assess the drain field. You can also request the original permit and design from the Vermont DEC regional office — this tells you the system\'s age and capacity.',resolvedWhen:'You have a recent inspection showing the system is functioning and the design capacity matches your intended use.',cost:'$300–$500 for pump-out and inspection. Free to request permit records.'},
    {title:'Well water — has it been tested recently?',whyCheck:'If the property has a private well (most rural Vermont homes do), water quality and flow rate matter. Vermont has naturally occurring arsenic in some areas. A clean test means you\'re good. A problem is fixable but costs $2,000–$8,000 for treatment.',howToResolve:'Get a water test from a state-certified lab. They\'ll send you a kit with instructions. Test for bacteria (coliform, E. coli) and minerals (arsenic, lead). Also ask about flow rate — under 3 gallons per minute can be limiting.',resolvedWhen:'You have a clean water test on file and flow rate is adequate.',cost:'$100–$400 for a comprehensive test. Results in 1–2 weeks.'},
    {title:'Heating — can this property be used beyond summer?',whyCheck:'Many Vermont seasonal homes were built for summer use only. If the heating is just a woodstove or a small propane heater, the property may not be safe to use in cold weather — pipes can freeze and burst, causing major damage. Upgrading heating also opens up shoulder-season rental income.',howToResolve:'Walk through the property and note the heating setup. Is there central heat? What fuel? Are water pipes in areas that could freeze? If the system is minimal, get a quote for a heat pump installation — Vermont rebates make this more affordable than most states.',resolvedWhen:'You know the heating system can keep the property above freezing when unoccupied, or you\'ve winterized the plumbing.',cost:'Free to assess yourself. Heat pump install: $3,000–$12,000 after rebates.'},
  ]
  if(p.isWaterfront)concerns.push({title:`Shoreline rules — what can you actually build near ${p.lakeName||'the water'}?`,whyCheck:`Vermont\'s Shoreland Protection Act limits what you can do within 250 feet of the water — clearing trees, adding patios, building additions. This doesn\'t mean you can\'t improve the property, but you need to know the boundaries before drawing up plans.`,howToResolve:`Get a property survey that shows the shoreland buffer zone. Call the ${p.town} zoning office and ask about local setback requirements. For anything beyond basic maintenance, you may need a shoreland permit from Vermont ANR.`,resolvedWhen:'You have a survey showing setbacks and know what requires a permit vs. what\'s allowed by right.',cost:'$500–$2,000 for a survey. Permit applications are $50–$200.'})
  concerns.push({title:'Property taxes — will improvements trigger a big increase?',whyCheck:`Seasonal homes in Vermont are taxed at a higher education tax rate than primary residences. That\'s normal. The question is whether your property is currently assessed close to market value. If it\'s under-assessed, major improvements could trigger a reappraisal that jumps your tax bill.`,howToResolve:`Pull your property\'s record card from the ${p.town} town clerk (often available online). Compare the assessed value to what similar properties have sold for recently.`,resolvedWhen:'You know your assessed value, understand the gap to market, and have modeled the tax impact of planned improvements.',cost:'Free. Town records are public.'})

  const actions:ActionItem[]=[
    {title:'Get the septic inspected',priority:'First',why:'Everything else — renovations, rentals, resale — goes smoother when you know this is solid. It\'s the single most important system to verify.',whatItUnlocks:'Confidence to plan renovations, ability to add bedrooms if capacity allows, clean path to sale or rental.',nextStep:'Call a licensed septic service in your area and schedule a pump-out with inspection.',timing:'Before planning any renovation.'},
    {title:'Test the well water',priority:'First',why:'Quick, cheap, and resolves one of the biggest unknowns. Either it\'s clean and you move on, or you catch a problem before it becomes a health issue.',whatItUnlocks:'Peace of mind, lender/rental compliance, baseline for the property.',nextStep:'Search "Vermont certified water testing labs" and order a test kit.',timing:'This month — results take 1–2 weeks.'},
    {title:'Walk the property and assess the heating',priority:'Before fall',why:'Understanding the heating situation tells you whether this is a 3-season or 4-season property — and what it would take to change that.',whatItUnlocks:'Shoulder-season and winter use, rental income potential, freeze protection confidence.',nextStep:'Note the heating type, fuel, and whether any water pipes run through unheated areas. If upgrading, get a heat pump quote.',timing:'Before October if you plan to use it in cold weather.'},
  ]
  if(p.isWaterfront)actions.splice(2,0,{title:'Understand what the shoreline rules allow',priority:'Before planning outdoor work',why:'Knowing the boundaries early prevents wasted design costs and permit surprises. Most waterfront improvements are doable — you just need to know the rules.',whatItUnlocks:'Ability to plan decks, docks, landscaping, and additions with realistic scope.',nextStep:`Call the ${p.town} zoning office and ask about shoreland setback requirements for your parcel.`,timing:'Before hiring a contractor for any outdoor work.'})
  actions.push({title:'Check your property tax situation',priority:'Before big spending',why:'Knowing where you stand on assessed value vs. market value helps you budget accurately — including the tax impact of improvements.',whatItUnlocks:'Accurate renovation budgeting, no surprise tax jumps.',nextStep:`Look up your property on the ${p.town} town clerk website or call the lister\'s office.`,timing:'Before committing to a renovation budget over $25,000.'})
  actions.push({title:'Look into energy rebates before upgrading heating or insulation',priority:'When ready to upgrade',why:'Vermont has unusually strong rebates. If you\'re going to upgrade anyway, stacking state and federal incentives can save 30–50% on the project.',whatItUnlocks:'Lower upgrade cost, reduced ongoing energy bills.',nextStep:'Visit efficiencyvermont.com/rebates and check what applies to your planned work.',timing:'When you\'re ready to move forward on heating or insulation.'})

  const avoidances:Avoidance[]=[
    {action:'Don\'t start a kitchen or bathroom renovation before checking the septic',why:'If the septic needs work, contractors may need to dig through areas you just renovated. Check the system first and save yourself from doing the work twice.'},
    {action:'Don\'t draw up addition plans before understanding setbacks and permits',why:`${p.isWaterfront?'Shoreline rules can change what\'s buildable. ':''}Getting plans drawn that don\'t comply with local rules means paying for design work you can\'t use.`},
    {action:'Don\'t prioritize cosmetic upgrades over system reliability',why:'A new kitchen in a house with a failing septic or no heat is a bad investment. Systems first, finishes second — especially in a seasonal property where the resale market rewards reliability over luxury.'},
  ]

  const seasonal:SeasonalItem[]=[]
  if(isWinter){seasonal.push({action:'Make sure the property is protected against freezing',why:'A burst pipe while the place is empty can cause tens of thousands in damage. Confirm heat is running or plumbing is drained.',timing:'Check now and weekly through winter.'});seasonal.push({action:'Clear heavy snow from the roof if the building is older',why:'Older roof framing may not handle extreme snow loads. Ice dams can cause interior leaks.',timing:'After major storms.'});seasonal.push({action:'Book contractors now for spring/summer work',why:'Vermont contractors fill up fast. Waiting until April means your project starts in July.',timing:'Now.'})}
  else if(isSummer){seasonal.push({action:'Get the septic pumped before hosting peak-season guests',why:'Heavy use on a system that hasn\'t been serviced in years increases the risk of backups.',timing:'Before Memorial Day.'});seasonal.push({action:'Test well water now if you haven\'t recently',why:'Better to know about any water quality issues before a summer of using it.',timing:'This month.'});seasonal.push({action:`Check if ${p.town} requires short-term rental registration`,why:'More Vermont towns are requiring registration. Better to be compliant than to get a fine.',timing:'Before listing.'})}
  else{seasonal.push({action:'Winterize before the first hard freeze',why:'Vermont can freeze as early as late September at elevation. Drain the plumbing or make sure heat can keep up.',timing:'By mid-October.'});seasonal.push({action:'Line up contractors now for spring work',why:'The good ones book months ahead. If you wait until spring, you\'re looking at summer start dates.',timing:'Now.'});seasonal.push({action:'Check roof and gutters before snow season',why:'Damaged gutters cause ice dams. Ice dams cause interior water damage.',timing:'Before first snowfall.'})}
  if(p.isWaterfront)seasonal.push({action:'Inspect the dock and shoreline',why:'Ice and storms shift things around. Check for damage before making repairs — unpermitted work in the shoreline zone can result in fines.',timing:isSummer?'Start of lake season.':'Spring, before putting the dock in.'})

  let reasoning=`These recommendations are based on how Vermont seasonal properties actually work: the systems below the surface — septic, well, heating — determine what the property can do and what it\'s worth. Most owners want to jump straight to visible improvements, but in this market, the smartest money goes to confirming the basics first. `
  if(p.isWaterfront)reasoning+=`Waterfront properties${p.lakeName?` on ${p.lakeName}`:''} are valuable but come with shoreline regulations worth understanding early. `
  if(p.isResort)reasoning+=`${p.town}\'s resort market adds rental income potential but also regulatory requirements worth checking. `
  reasoning+=`The actions above are sequenced so that each step either confirms you\'re in good shape or catches a problem before it gets expensive.`

  const programs:ProgramScreen[]=[
    {name:'Efficiency Vermont Rebates',why:'If you\'re upgrading heating or insulation, these rebates offset $500–$4,000 of the cost. Heat pump rebates are especially strong.',value:'$500–$4,000',caveat:'Requires specific equipment and participating contractors. Check current terms first.',url:'https://www.efficiencyvermont.com/rebates'},
    {name:'Federal Clean Energy Tax Credit',why:'Heat pumps and insulation qualify for a 30% federal tax credit on top of state rebates.',value:'Up to $3,200/year',caveat:'Second homes have some eligibility limits. Worth confirming with a tax advisor.'},
    {name:'Vermont Weatherization Program',why:'Free insulation and air sealing for income-eligible homeowners. Even if you don\'t qualify for free services, market-rate weatherization is available.',value:'Free if eligible, or $3,000–$8,000 market rate',caveat:'Income limits apply. Wait times can be 6–12 months for the free program.'},
  ]

  return{summary,snapshot:{address:`${p.street}, ${p.town}, ${p.county} County, VT`,town:p.town,county:p.county,facts},strengths,concerns,actions,avoidances,seasonal,reasoning,programs,generatedAt:new Date().toISOString()}
}

export async function POST(req:NextRequest){try{const{address}=await req.json();if(!address||address.trim().length<3)return NextResponse.json({error:'Please enter an address.',suggestion:'Example: 142 Lakeshore Drive, Greensboro, VT'},{status:400});const result=parse(address);if(!result.ok||!result.parsed)return NextResponse.json({error:result.error,suggestion:result.suggestion},{status:400});return NextResponse.json(buildReport(result.parsed))}catch{return NextResponse.json({error:'Analysis failed. Please try again.'},{status:500})}}
