/**
 * v7.3.4-PR3 — Photo cart synthesis at Stripe webhook time.
 *
 * Called by the Stripe webhook when a checkout.session.completed event
 * arrives with metadata.product_source === 'photo'. Pulls the
 * visitor's recent VisionExtractions (24h window, scoped by anonId),
 * runs synthesizeCartV3, persists a SmartCart row with the provided
 * cartId so /smart-cart/result/[cartId] can render it via the v3
 * dispatch added in v7.3.4-PR1.
 *
 * Distinct from /api/cart/synthesize because:
 *   - That route is the free-beta path (anon, no payment, anon
 *     cookie auth).
 *   - This is the paid path (post-Stripe, runs server-side from a
 *     webhook context with no cookie, identified by the anonId that
 *     came through Stripe metadata).
 *   - The cartId here is the human-readable CART-XXXXXX format
 *     generated by /api/smart-cart/checkout, NOT a cuid. We override
 *     the Prisma default by passing { id: cartId } in the create.
 */

import { prisma } from '@/lib/db'
import { isOpenExtractionShape, type OpenExtraction, type OpenFeature } from '@/lib/vision/prompt'
import { synthesizeCartV3, type SynthCartItemV3 } from '@/lib/smart-cart/synthesize-v3'
import { logEvent } from '@/lib/events/log'

const RECENT_PHOTO_WINDOW_MS = 24 * 60 * 60 * 1000 // 24h

export interface BuildCartFromPhotosOptions {
  cartId: string // CART-XXXXXX format from checkout
  anonId: string
  customerEmail: string
}

export interface BuildCartFromPhotosResult {
  cartId: string
  itemCount: number
  photoCount: number
  featureCount: number
  cacheHits: number
  cacheMisses: number
  llmCallsRan: number
  llmTotalCostCents: number
  llmTotalLatencyMs: number
  items: SynthCartItemV3[]
}

export async function buildCartFromPhotos(
  opts: BuildCartFromPhotosOptions
): Promise<BuildCartFromPhotosResult> {
  const since = new Date(Date.now() - RECENT_PHOTO_WINDOW_MS)

  const photos = await prisma.photo.findMany({
    where: {
      visitorAnonId: opts.anonId,
      blobConfirmedAt: { not: null },
      uploadedAt: { gte: since },
    },
    include: {
      extractions: { orderBy: { createdAt: 'desc' }, take: 1 },
    },
    orderBy: { uploadedAt: 'desc' },
  })

  const features: OpenFeature[] = []
  let photosWithExtractions = 0
  for (const photo of photos) {
    const ex = photo.extractions[0]
    if (!ex) continue
    const json = ex.extractionJson as unknown
    if (!isOpenExtractionShape(json)) continue
    photosWithExtractions += 1
    features.push(...(json as OpenExtraction).features)
  }

  // PR3.10: pull the visitor's project FIRST so we can pass its
  // userIntent into synthesis. The project resolution was already
  // happening below but only used for its id; reading userIntent
  // here keeps the synth call intent-aware.
  const project = await prisma.project.findFirst({
    where: { visitorAnonId: opts.anonId },
    orderBy: { createdAt: 'desc' },
  })

  // The webhook should never have arrived if the visitor had no
  // photos extracted — the photo panel gates on photoCount > 0 +
  // confidence threshold before showing the paywall CTA. But
  // defensive code: if features array is empty, synthesizeCartV3
  // returns an empty cart and we still persist it so the visitor
  // gets a refund-eligible "we had no data to work with" row.
  const result = await synthesizeCartV3({
    features,
    userIntent: project?.userIntent ?? null,
  })

  if (!project) {
    // Synthesize without a project. SmartCart.projectId is required
    // by the schema so this would error. Better: create a Project
    // shell record now so the SmartCart can attach.
    throw new Error(
      `buildCartFromPhotos: no Project for anon ${opts.anonId} — was the upload pipeline run?`
    )
  }

  // Persist with the human-readable cartId as the row's id, so
  // /smart-cart/result/[cartId] can find it via Prisma.findUnique.
  // visitorAnonId is preserved for the email-claim flow that runs
  // separately (PR3.5 / v7.3.4 followup).
  const cart = await prisma.smartCart.create({
    data: {
      id: opts.cartId,
      projectId: project.id,
      visitorAnonId: opts.anonId,
      synthesisVersion: 'v3_learning_store',
      photoCount: photosWithExtractions,
      photoAttached: features.length > 0,
      cartJson: result.withPhotos as never,
      cartItemsJsonWithoutPhotos: result.withoutPhotos as never,
      cartItemsJsonWithPhotos: result.withPhotos as never,
      photoChangedRecommendation: result.photoChangedRecommendation,
      // v7.3.4-PR3.6 — introText lives inside the existing
      // changeSummaryJson column. PR3.7 §1.2 + §1.4 + §1.6 add
      // needsCategoryClarification + needsMorePhotos + clarification
      // features so the result page renders the right state without
      // needing to recompute.
      changeSummaryJson: {
        ...result.changeSummary,
        introText: result.introText,
        needsCategoryClarification: result.needsCategoryClarification,
        needsMorePhotos: result.needsMorePhotos,
        clarificationFeatures: result.clarificationFeatures,
        dominantCategory: result.dominantCategory,
        dominantCategoryConfidence: result.dominantCategoryConfidence,
      } as never,
    },
  })

  // PR3.7 §1.12: log CART_INSUFFICIENT_SIGNAL when the customer paid
  // and we landed in needsMorePhotos / needsCategoryClarification —
  // helps the retro decide whether to tighten extraction quality or
  // add a category-clarification step earlier in the funnel.
  if (result.needsMorePhotos || result.needsCategoryClarification) {
    try {
      await logEvent({
        eventType: 'CART_INSUFFICIENT_SIGNAL',
        subjectType: 'SmartCart',
        subjectId: cart.id,
        anonId: opts.anonId,
        source: 'system',
        payload: {
          gate: result.needsCategoryClarification
            ? 'ambiguous_category'
            : 'empty_buy_lane',
          dominantCategory: result.dominantCategory,
          dominantCategoryConfidence: result.dominantCategoryConfidence,
          featureCount: features.length,
        },
      })
    } catch {
      /* swallow */
    }
  }

  await logEvent({
    eventType: 'PHOTO_CART_PAID',
    subjectType: 'SmartCart',
    subjectId: cart.id,
    anonId: opts.anonId,
    source: 'system',
    payload: {
      cartId: cart.id,
      customerEmail: opts.customerEmail,
      photoCount: photosWithExtractions,
      featureCount: features.length,
      itemCount: result.withPhotos.length,
      cacheHits: result.meta.cacheHits,
      cacheMisses: result.meta.cacheMisses,
      llmCallsRan: result.meta.llmCallsRan,
      llmTotalCostCents: result.meta.llmTotalCostCents,
      llmTotalLatencyMs: result.meta.llmTotalLatencyMs,
    },
  })

  return {
    cartId: cart.id,
    itemCount: result.withPhotos.length,
    photoCount: photosWithExtractions,
    featureCount: features.length,
    cacheHits: result.meta.cacheHits,
    cacheMisses: result.meta.cacheMisses,
    llmCallsRan: result.meta.llmCallsRan,
    llmTotalCostCents: result.meta.llmTotalCostCents,
    llmTotalLatencyMs: result.meta.llmTotalLatencyMs,
    items: result.withPhotos,
  }
}
