// V7.2.5 — Trimmed home_water_quality scope catalog.
//
// Generated by scripts/ingest-catalog.ts from
// scripts/source-catalogs/home-water-quality.ts.
// Editorial layer only. Product data lives in
// src/content/smart-cart/universe.ts.

import type { ScopeCatalog } from '@/lib/smart-cart-model'

export const HOME_WATER_QUALITY: ScopeCatalog = {
  "topic": "home_repair",
  "scopeVariantId": "home_water_quality",
  "scenarios": [
    "just_starting",
    "already_have_basics",
    "tight_budget",
    "absentee_owner"
  ],
  "slots": [
    {
      "slotId": "water_basic_test_strips",
      "slotLabel": "Basic test strips (screening only)",
      "slotKind": "core",
      "conditionalOn": [
        "has_recent_lab_test"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "water_test_kit",
            "basic_test_strips"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_lab_test",
          "tier": "budget",
          "limit": 1
        }
      },
      "whyThis": "Watersafe is the consumer standard. Cross-scope reuse from outdoor_seasonal_opening.",
      "whyNotCheaper": "Cheaper strips are pH-only or hardness-only. The Watersafe all-in-one is the right balance.",
      "whyNotPremium": "There's no premium tier in strip-format. The premium answer is the lab test, not a fancier strip.",
      "contextNote": "Strips are screening only. They are not reliable for bacteria detection, low-concentration metals, or radon. Positive screen → confirm with lab; negative screen → still get an annual lab test for the things strips can't see.",
      "citations": [
        "Cross-scope universe reuse pattern",
        "Watersafe product documentation",
        "EPA private well testing guidance"
      ],
      "slotPurpose": "Quick at-home screen for major contaminant categories. NOT a substitute for lab analysis on bacteria or trace metals.",
      "whyItMatters": "Strips give a fast read on whether anything obvious is wrong — high hardness, chlorine in well water (shouldn't be), nitrate spike. Useful as a baseline before deciding whether to spend on a lab test.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "lab_water_test",
        "reason": "Strips screen for the obvious. The lab test catches the things strips miss — bacteria, low-level metals, radon-in-water."
      }
    },
    {
      "slotId": "water_lab_test",
      "slotLabel": "Mail-in lab water test (well water panel)",
      "slotKind": "core",
      "conditionalOn": [
        "has_recent_lab_test",
        "on_municipal_water"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "water_test_kit",
            "lab_water_test"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_lab_test",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "water_test_kit",
            "lab_water_test"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_lab_test",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Tap Score Essential covers Vermont-specific concerns (radon, arsenic, manganese, bacteria, hardness) at a price comparable to one bottled-water case. Cross-scope reuse from outdoor_seasonal_opening.",
      "contextNote": "Vermont DEC publishes regional water quality data. Check your county's public data first to see what's likely. Then use the lab test to confirm for your specific well.",
      "citations": [
        "Cross-scope universe reuse pattern",
        "Tap Score by SimpleLab documentation",
        "Vermont DEC water quality regional data"
      ],
      "slotPurpose": "Test for what's actually in your water before deciding what to filter.",
      "whyItMatters": "Filters target specific contaminants. A sediment filter doesn't remove arsenic; an arsenic filter doesn't remove bacteria. Without a lab test, you're guessing — and the guess is usually wrong.",
      "commonMistake": "Buying a 'whole-house water treatment system' before testing. These systems range from $1,500-$5,000 installed. They might solve your problem or they might solve the wrong one. Test first.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "sediment_filter",
        "reason": "You have current test results. Build the right filter system based on what the test showed — sediment filter for silt, carbon for chlorine/taste, RO for arsenic, etc."
      }
    },
    {
      "slotId": "water_bacteria_test",
      "slotLabel": "Bacteria-specific test kit",
      "slotKind": "addon",
      "conditionalOn": [
        "has_recent_bacteria_test"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "bacteria_test_kit"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_bacteria_test",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Mail-in or incubation bacteria-only kits are cheaper than full panels and let you test more often. Run after well work, after flood events, or anytime taste changes.",
      "whyNotCheaper": "Free state-laboratory testing exists in some counties. Check Vermont Department of Health first; if a free test is available, use it.",
      "whyNotPremium": "Bacteria testing is binary: present or not. Premium versions offer faster turnaround but no different result quality.",
      "contextNote": "Test bacteria after any well work, lightning strike near the well, flooding, or unusual taste/smell change. Don't wait for an annual cycle if conditions changed.",
      "citations": [
        "Vermont DEC private well bacteria testing guidance"
      ],
      "slotPurpose": "Stand-alone bacteria test between annual full panels.",
      "whyItMatters": "Vermont DEC recommends annual bacteria testing for private wells and every 5 years for chemistry. The bacteria test is the higher-frequency check; the full panel is the deeper check.",
      "routeOutOfSmartCartIf": [
        {
          "condition": "has_bacteria_positive_test",
          "destination": "small_pro",
          "reason": "Positive bacteria test means shock chlorination of the well + retest, or installing UV/chlorine treatment. Well-pump pro work."
        }
      ]
    },
    {
      "slotId": "water_sediment_filter",
      "slotLabel": "Whole-house sediment filter",
      "slotKind": "core",
      "conditionalOn": [
        "has_sediment_filter"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "filter_replacement",
            "sediment_filter"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_sediment_filter",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "filter_replacement",
            "sediment_filter"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_sediment_filter",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "filter_replacement",
            "sediment_filter"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_sediment_filter",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Cross-scope reuse from outdoor_seasonal_opening. Pentek 2-pack (sediment + carbon) is the right tier for typical Vermont well water.",
      "contextNote": "Sediment filter is the foundation. Add carbon for taste/chlorine, RO for trace metals or arsenic, UV for bacteria. Always start with sediment — it protects everything downstream.",
      "citations": [
        "Cross-scope universe reuse pattern",
        "Pentek product documentation"
      ],
      "slotPurpose": "Remove silt, rust, and visible particulates from incoming water.",
      "whyItMatters": "Sediment shortens the life of every downstream fixture. Even if your water is clean of contaminants, sediment damages valves, water heaters, washing machine pumps, and any point-of-use filter."
    },
    {
      "slotId": "water_fridge_filter",
      "slotLabel": "Refrigerator water filter (point-of-use)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_fridge_filter_compatible"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "fridge_filter"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_fridge_filter_compatible",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "fridge_filter"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_fridge_filter_compatible",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "OEM filters fit reliably and meet NSF certifications. Generic 'compatible' filters are a real coin flip on fit and quality.",
      "whyNotCheaper": "Generic filters at 50% the price are tempting. Reviews show ~30% report fit issues or leaking. The OEM premium buys reliability.",
      "whyNotPremium": "Premium 'lifetime' filters don't exist for this category — all are 6-month consumables.",
      "contextNote": "Replace every 6 months even if water still tastes fine. Carbon filters lose effectiveness on a time basis, not a usage basis. The filter housing date stamp matters more than the visible cleanliness.",
      "citations": [
        "NSF certification standards for refrigerator filters"
      ],
      "slotPurpose": "Final taste/odor polish at the kitchen tap. Useful even with whole-house filtration.",
      "whyItMatters": "Fridge filters target taste and odor at the point of consumption. They are a luxury add-on if whole-house filtration is in place; they are essential if there's no whole-house filter and the issue is taste only.",
      "commonMistake": "Buying generic universal fridge filters. Many have poor fit and bypass water around the filter, defeating the entire point. Either OEM or use a verified-compatible brand (e.g., Aqua Crest with documented fit testing)."
    },
    {
      "slotId": "water_drinking_filter",
      "slotLabel": "Drinking water filter (pitcher or under-sink)",
      "slotKind": "core",
      "conditionalOn": [
        "has_drinking_water_filter"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "drinking_water_filter"
          ],
          "mustHaveRoles": [
            "appliance",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_drinking_water_filter",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "drinking_water_filter"
          ],
          "mustHaveRoles": [
            "appliance",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_drinking_water_filter",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "drinking_water_filter"
          ],
          "mustHaveRoles": [
            "appliance",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_drinking_water_filter",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "ZeroWater is the verified upgrade over Brita for households concerned about lead or heavy metals. The included TDS meter is the actual differentiator — you see when the filter is exhausted.",
      "whyNotCheaper": "Brita Standard works but doesn't address heavy metals. If your test shows any concern, ZeroWater is the right tier.",
      "whyNotPremium": "Aquasana under-sink is the right call for high-volume households or for filtering directly from the tap. Pitcher solutions cap at ~3 gallons/day reasonably; under-sink scales unlimited.",
      "citations": [
        "NSF certification standards for drinking water pitchers",
        "ZeroWater contaminant reduction documentation",
        "Aquasana AQ-5300+ specifications"
      ],
      "slotPurpose": "Drinking water that tastes right and removes the contaminants you actually have.",
      "whyItMatters": "Brita is fine for taste/chlorine. ZeroWater handles taste plus reduces lead and other heavy metals. Aquasana is the under-sink system for households drinking 10+ gallons/week. Match the filter to your test results, not your shopping list.",
      "commonMistake": "Pitcher filter when the issue is sediment or arsenic. Pitchers don't address either. Sediment kills the filter cartridge faster; arsenic isn't removed by activated carbon. Read your test results first."
    },
    {
      "slotId": "water_filter_wrench",
      "slotLabel": "Filter housing wrench + spare O-ring",
      "slotKind": "addon",
      "conditionalOn": [
        "has_filter_wrench"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "filter_wrench"
          ],
          "mustHaveRoles": [
            "tool"
          ],
          "excludeAlreadyHaveFlag": "has_filter_wrench",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "$15 prevents 30-60 minutes of frustration plus a hardware store run. The silicone grease keeps O-rings supple — apply at every filter change.",
      "whyNotCheaper": "Generic wrenches without spare O-rings save $5; you need the O-rings anyway.",
      "whyNotPremium": "There's no premium tier for this product category.",
      "contextNote": "Apply silicone grease (provided) to the O-ring at every filter change. Dry O-rings tear; greased ones last 5+ replacement cycles.",
      "citations": [
        "Filter housing maintenance guidance"
      ],
      "slotPurpose": "Open the filter housing without breaking it, with replacement O-rings on hand.",
      "whyItMatters": "Filter housings tighten over time. Without the wrench, you can't get them off. Without spare O-rings, when the original O-ring fails (and they always do), you're driving to the hardware store with water dripping.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "pressure_gauge",
        "reason": "You can service filter housings. The next-step gap is monitoring pressure — a gauge tells you when a filter is clogged before flow drops noticeably."
      }
    },
    {
      "slotId": "water_pressure_gauge",
      "slotLabel": "Water pressure gauge (hose-bib mount)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_pressure_gauge"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "pressure_gauge"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "tool"
          ],
          "excludeAlreadyHaveFlag": "has_pressure_gauge",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Hose-bib gauge is the cheapest reliable diagnostic tool in plumbing. Screw it on, read the number, you know if pressure is in spec (40-80 PSI normal) or out.",
      "whyNotCheaper": "Sub-$8 gauges are unreliable. The $12 mid-range gauge lasts a decade.",
      "whyNotPremium": "Continuous-monitoring smart pressure sensors exist. For occasional diagnostic use, the analog gauge is right-sized.",
      "contextNote": "Read pressure both before and after filters. A 20+ PSI drop across a filter means it's clogged.",
      "citations": [
        "Water pressure diagnosis guidance"
      ],
      "slotPurpose": "Check incoming water pressure to diagnose system issues.",
      "whyItMatters": "Low water pressure can mean clogged filter, failing pressure tank, or supply issue. The $12 gauge tells you which problem you have. Without it you're guessing."
    }
  ],
  "skipList": [
    {
      "id": "skip_filter_no_test_first",
      "type": "wrong_version",
      "title": "Buying filter system before water testing",
      "marketingPitch": "Comprehensive whole-house water treatment.",
      "realReason": "Filters target specific contaminants. A $2,500 system that addresses chlorine when your real problem is arsenic doesn't fix arsenic. Test first, then size and select the system. The lab test ($165) is the highest-leverage spend in this entire scope.",
      "amountSaved": {
        "low": 1500,
        "high": 4500
      },
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "EPA water treatment selection guidance"
      ]
    },
    {
      "id": "skip_pitcher_for_sediment",
      "type": "wrong_version",
      "title": "Pitcher filter when the issue is sediment",
      "marketingPitch": "Convenient counter-top water filtration.",
      "realReason": "Pitcher filters address taste, chlorine, some metals. They don't address sediment — sediment clogs the pitcher filter within weeks instead of months and provides no real protection. If you have visible particulates, install a whole-house sediment filter; the pitcher is downstream.",
      "amountSaved": {
        "low": 25,
        "high": 60
      },
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "Filter type vs contaminant matching"
      ]
    },
    {
      "id": "skip_under_sink_ro_no_test",
      "type": "wrong_version",
      "title": "Under-sink reverse osmosis (RO) before water test",
      "marketingPitch": "99% pure drinking water.",
      "realReason": "RO removes nearly everything — including beneficial minerals. It's the right answer if you have arsenic, fluoride, or specific metals to address. It's expensive overkill ($300-$600 + filter replacement costs) if your test shows only chlorine taste. Test first.",
      "amountSaved": {
        "low": 200,
        "high": 500
      },
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "RO system contaminant matching"
      ]
    },
    {
      "id": "skip_universal_fridge_filter",
      "type": "wrong_version",
      "title": "\"Universal\" generic fridge filters",
      "marketingPitch": "Compatible with all refrigerators, half the price of OEM.",
      "realReason": "30%+ of generic 'universal' fridge filters report fit issues. Water bypasses around the filter, you get unfiltered water, and you don't know it. Either OEM or use a verified-compatible brand (Aqua Crest with documented fit testing).",
      "amountSaved": {
        "low": 15,
        "high": 30
      },
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "Fridge filter compatibility data"
      ]
    },
    {
      "id": "skip_taste_as_safety",
      "type": "wrong_version",
      "title": "Treating water taste as a safety indicator",
      "marketingPitch": "\"Tastes great, must be safe.\"",
      "realReason": "Water that tastes fine can have invisible bacteria, lead, arsenic, or radon. Water that tastes bad can be perfectly safe but contain harmless chlorine. Taste is not a safety signal. Annual lab testing is the safety check.",
      "amountSaved": {
        "low": 0,
        "high": 0
      },
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "EPA private well safety guidance"
      ]
    },
    {
      "id": "skip_municipal_water_lab_test",
      "type": "wrong_category",
      "title": "Lab tests for municipal water",
      "realReason": "Municipal water systems test continuously and publish results. Vermont's annual reports are publicly available. Homeowner lab tests on municipal water duplicate work the utility already does. Read the utility's annual Consumer Confidence Report; save the $165.",
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "EPA municipal water testing requirements"
      ]
    },
    {
      "id": "skip_water_softener_no_hardness",
      "type": "wrong_category",
      "title": "Water softener without hardness test",
      "realReason": "Softeners address hardness — calcium and magnesium. They don't help with bacteria, metals, sediment, taste. Vermont well hardness varies widely by region; some areas have soft water that doesn't need softening. Test hardness; only buy a softener if test shows it's actually needed.",
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "Water softener applicability"
      ]
    },
    {
      "id": "skip_alkaline_water_devices",
      "type": "wrong_category",
      "title": "Alkaline / \"ionized\" / \"structured\" water devices",
      "realReason": "$300-$3,000 devices that claim to alter water at the molecular level for health benefits. The peer-reviewed evidence does not support the health claims. Skip in favor of lab-tested filtration that addresses real contaminants.",
      "appliesToScope": [
        "home_water_quality"
      ],
      "citations": [
        "Peer-reviewed alkaline water health-claim analysis"
      ]
    }
  ],
  "scenarioDefaults": {
    "just_starting": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    },
    "already_have_basics": {
      "selectedTier": "sweet_spot",
      "alreadyHave": [
        "has_recent_lab_test",
        "has_sediment_filter"
      ]
    },
    "tight_budget": {
      "selectedTier": "budget",
      "alreadyHave": []
    },
    "absentee_owner": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    }
  },
  "smartCartPromise": "Test before treating. Avoid buying the wrong filter for the wrong water problem.",
  "primaryCustomerPain": "Vermont rural homes are mostly on private wells. Water quality varies by region (arsenic in some areas, radon-in-water in others, manganese, iron, hardness everywhere). Buying a filter system without testing first means you almost always solve the wrong problem.",
  "valueProposition": "A $165 lab test plus the right targeted filter system ($75-$250) replaces a $2,500 whole-house treatment system that addressed the wrong contaminant. Test first, treat right.",
  "routeOutRules": [
    {
      "condition": "has_bacteria_positive_test",
      "destination": "small_pro",
      "reason": "Positive bacteria test (E. coli, total coliform) requires shock chlorination of the well, then UV treatment or chlorine injection. This is well-pump pro work, not Smart Cart."
    },
    {
      "condition": "has_arsenic_above_mcl",
      "destination": "small_pro",
      "reason": "Arsenic above the EPA MCL of 10 ppb requires specific reverse osmosis or adsorption media — sized to your usage and tested for breakthrough. Pro consultation, not a $50 pitcher filter."
    },
    {
      "condition": "has_radon_in_water_high",
      "destination": "small_pro",
      "reason": "Radon in water above ~4,000 pCi/L typically requires aeration treatment — engineered system, not point-of-use. Vermont DEC has a regional radon program; consult them first."
    }
  ]
}
