// V7.2.5 — Trimmed home_moisture_control scope catalog.
//
// Generated by scripts/ingest-catalog.ts from
// scripts/source-catalogs/home-moisture-control.ts.
// Editorial layer only. Product data lives in
// src/content/smart-cart/universe.ts.

import type { ScopeCatalog } from '@/lib/smart-cart-model'

export const HOME_MOISTURE_CONTROL: ScopeCatalog = {
  "topic": "home_repair",
  "scopeVariantId": "home_moisture_control",
  "scenarios": [
    "just_starting",
    "already_have_basics",
    "tight_budget",
    "absentee_owner"
  ],
  "slots": [
    {
      "slotId": "moisture_hygrometer",
      "slotLabel": "Hygrometer (humidity monitor)",
      "slotKind": "core",
      "conditionalOn": [
        "has_hygrometer"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "hygrometer"
          ],
          "mustHaveRoles": [
            "sensor",
            "monitor",
            "measurement_tool"
          ],
          "excludeAlreadyHaveFlag": "has_hygrometer",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "hygrometer"
          ],
          "mustHaveRoles": [
            "sensor",
            "monitor",
            "measurement_tool"
          ],
          "excludeAlreadyHaveFlag": "has_hygrometer",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "hygrometer"
          ],
          "mustHaveRoles": [
            "sensor",
            "monitor",
            "measurement_tool"
          ],
          "excludeAlreadyHaveFlag": "has_hygrometer",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Govee WiFi 3-pack covers the three moisture-prone zones (basement, primary bath, utility room) and sends app alerts when humidity exceeds threshold. The historical graphs are the actual product — you see when humidity spikes (storms, baths, cooking) vs steady-state.",
      "whyNotCheaper": "AcuRite single is fine if you only have one room of concern and you check it daily. For absentee owners or whole-house monitoring, WiFi alerts are the real value.",
      "whyNotPremium": "SensorPush is genuinely more accurate but the marginal benefit isn't useful for mold prevention (60% threshold). Worth it for humidor or instrument-storage applications, not for residential mold prevention.",
      "contextNote": "Set alert threshold at 60% humidity. Below 60%, mold can't grow. Above, the clock is ticking. The alert lets you act before mold appears.",
      "citations": [
        "Govee WiFi Hygrometer documentation",
        "AcuRite product line",
        "SensorPush HTP.xw specifications",
        "EPA mold growth thresholds"
      ],
      "slotPurpose": "Continuously measure humidity in spaces that grow mold (basements, crawlspaces, bathrooms) so you see problems before they become visible.",
      "whyItMatters": "Mold grows above 60% relative humidity. By the time you smell mold, humidity has been above 60% for weeks. A hygrometer catches the trend at week 1 instead of week 4.",
      "commonMistake": "Single-room hygrometer when the moisture problem is whole-house. Vermont basements often have humidity 20-30% higher than the upstairs. One sensor doesn't tell the whole story.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "moisture_meter",
        "reason": "You're tracking ambient humidity. The next-step gap is wood/drywall moisture meter — measures specific surface moisture in walls and floors where the hygrometer doesn't reach."
      }
    },
    {
      "slotId": "moisture_dehumidifier",
      "slotLabel": "Whole-basement dehumidifier (50-pint)",
      "slotKind": "core",
      "conditionalOn": [
        "has_dehumidifier"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "dehumidifier_entry",
            "dehumidifier_whole"
          ],
          "mustHaveRoles": [
            "appliance",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_dehumidifier",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "dehumidifier_entry",
            "dehumidifier_whole"
          ],
          "mustHaveRoles": [
            "appliance",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_dehumidifier",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "dehumidifier_entry",
            "dehumidifier_whole"
          ],
          "mustHaveRoles": [
            "appliance",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_dehumidifier",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Cross-scope reuse from outdoor_seasonal_opening. hOmeLabs 50-pint with continuous drain is the verified pick for Vermont basements. Place near the highest-humidity reading from your hygrometer monitoring.",
      "contextNote": "Dehumidifier should be sized to the space. 30-pint for ~1,500 sq ft basements. 50-pint for typical Vermont 2,500 sq ft basements with high moisture load. Aprilaire whole-house is integrated with HVAC for total home coverage.",
      "citations": [
        "Cross-scope universe reuse pattern (v7.2.4 architecture)",
        "hOmeLabs 50-pint product documentation"
      ],
      "slotPurpose": "Active humidity reduction in moisture-prone spaces.",
      "whyItMatters": "When ambient humidity exceeds 60% during summer humidity peaks or after spring snowmelt, the dehumidifier is what brings it back to safe levels. Without active dehumidification, summer Vermont basements stay above 70% for months."
    },
    {
      "slotId": "moisture_meter",
      "slotLabel": "Wood / drywall moisture meter",
      "slotKind": "core",
      "conditionalOn": [
        "has_moisture_meter"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "moisture_meter"
          ],
          "mustHaveRoles": [
            "measurement_tool"
          ],
          "excludeAlreadyHaveFlag": "has_moisture_meter",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "General Tools MMD4E is the verified residential moisture meter. Cross-scope reuse — same entry serves outdoor_deck_refresh and home_moisture_control.",
      "whyNotCheaper": "Sub-$20 meters give inconsistent readings.",
      "whyNotPremium": "Pro-grade meters are unnecessary for residential diagnosis.",
      "contextNote": "Wood at 15%+ moisture and drywall at 17%+ are 'wet' for our purposes. Below those levels, ambient humidity is the issue (use dehumidifier). Above, there's a water source (route to pro).",
      "citations": [
        "Cross-scope universe reuse pattern",
        "General Tools MMD4E specifications"
      ],
      "slotPurpose": "Measure surface moisture in wood and drywall. Distinguishes 'dry, just musty smell' from 'actively wet, moisture source somewhere'.",
      "whyItMatters": "Hygrometer measures air humidity. Moisture meter measures actual material moisture. If a wall reads 22% moisture, there's water IN the wall — not just humid air. That's a different problem with a different fix."
    },
    {
      "slotId": "moisture_mold_test",
      "slotLabel": "Mold test kit (DIY screening only)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_recent_mold_test"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "mold_test_kit"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_mold_test",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "DIY kit is the screening tool. If results show common mold genera in concerning concentrations, the next step is pro inspection. If results are clean, the smell is something else (organic decay, dampness without mold).",
      "contextNote": "Visible mold over ~10 sq ft is per-EPA-guidance professional remediation territory. Don't DIY remediate large mold; you spread spores. Get a pro. (Pro inspection runs $250-600 and is not a Smart Cart purchase — it's a service call.)",
      "citations": [
        "EPA mold remediation guidance",
        "My Mold Detective product documentation"
      ],
      "slotPurpose": "Screen for mold presence when you have musty smell but no visible mold.",
      "whyItMatters": "Visible mold = pro inspection. Smell without visible mold = DIY screening can identify whether mold is present and what type. The DIY result then informs whether to call a pro.",
      "commonMistake": "Buying a DIY mold test as a substitute for pro inspection when you have visible mold. The DIY kit is screening; the pro inspection is diagnosis. They're not the same product.",
      "routeOutOfSmartCartIf": [
        {
          "condition": "has_visible_mold_over_10_sqft",
          "destination": "small_pro",
          "reason": "EPA guidance: mold larger than ~10 sq ft is professional remediation. DIY removal spreads spores throughout the house."
        }
      ]
    },
    {
      "slotId": "moisture_odor_absorber",
      "slotLabel": "Activated charcoal odor absorber",
      "slotKind": "core",
      "conditionalOn": [
        "has_odor_absorber"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "odor_absorber"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "cleaner"
          ],
          "excludeAlreadyHaveFlag": "has_odor_absorber",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Moso bamboo charcoal is the verified Wirecutter pick. Reusable (sun-dry monthly to reactivate). Lasts 2 years with proper maintenance. Per-month cost is ~$1.",
      "whyNotCheaper": "Cheap charcoal bags use lower-quality charcoal that loses adsorption capacity within months.",
      "whyNotPremium": "Premium ($60+) air purification systems are for active filtration of allergens. For odor adsorption, the bags do the job.",
      "contextNote": "Charcoal works AFTER the moisture source is addressed. If you put charcoal in a damp basement without dehumidifier, it adsorbs moisture and saturates within 2-4 weeks. Fix moisture first, then deploy charcoal.",
      "citations": [
        "Moso bamboo charcoal product documentation",
        "Wirecutter air purifier and odor absorber testing"
      ],
      "slotPurpose": "Absorb residual odors after addressing moisture source. The 'mop up' step after dehumidifier and ventilation.",
      "whyItMatters": "Even after fixing the moisture source, the smell can linger in fabric and wood. Charcoal physically adsorbs the odor molecules — doesn't mask them like air fresheners do.",
      "commonMistake": "Using scented air fresheners to cover smells. Plug-ins, sprays, candles. They mask the smell while the underlying moisture problem worsens. The charcoal solution is removal; the air freshener is theater."
    },
    {
      "slotId": "moisture_air_mover",
      "slotLabel": "Air mover / circulation fan",
      "slotKind": "addon",
      "conditionalOn": [
        "has_air_mover"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "home_repair"
          ],
          "mustHaveFunctions": [
            "air_mover"
          ],
          "mustHaveRoles": [
            "appliance"
          ],
          "excludeAlreadyHaveFlag": "has_air_mover",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Lasko 3300 is the standard residential air mover. Strong enough to move air across a basement, quiet enough to leave running. ~$70 once.",
      "whyNotCheaper": "Small desk fans don't move enough air to dry a basement. The 20-inch wind machine is the right scale.",
      "whyNotPremium": "Industrial air movers exist for water-damage restoration. For preventive moisture control, the residential fan is sufficient.",
      "citations": [
        "Lasko 3300 product documentation"
      ],
      "slotPurpose": "Move air through closed/stagnant spaces (basements, crawlspaces, closed-up second homes) to dry surfaces and prevent humidity stagnation.",
      "whyItMatters": "Dehumidifier removes water from the air. Air mover circulates the air so the dehumidifier reaches all corners. Without circulation, the dehumidifier dries the immediate area while distant corners stay damp."
    },
    {
      "slotId": "moisture_leak_sensor",
      "slotLabel": "WiFi water leak sensor (cross-scope reuse)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_leak_detection"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor",
            "home_repair"
          ],
          "mustHaveFunctions": [
            "leak_detector"
          ],
          "mustHaveRoles": [
            "sensor"
          ],
          "excludeAlreadyHaveFlag": "has_leak_detection",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Cross-scope reuse from outdoor_freeze_prevention. Place sensors near water heater, washing machine, sump pump, under sinks.",
      "citations": [
        "Cross-scope universe reuse pattern",
        "Govee H5054 product documentation"
      ],
      "slotPurpose": "Detect a leak that's contributing to moisture problems. Often the cause of persistent damp/musty smell is an undetected slow leak.",
      "whyItMatters": "If your basement humidity won't go below 65% even with dehumidifier running 24/7, there's a water source. A slow leak from a water heater, washing machine, or supply line adds enough water to defeat the dehumidifier."
    }
  ],
  "skipList": [
    {
      "id": "skip_dehumidifier_water_source_unknown_moisture",
      "type": "wrong_version",
      "title": "Dehumidifier before identifying water source",
      "marketingPitch": "Whole-basement humidity solution.",
      "realReason": "Dehumidifiers treat ambient moisture from condensation and air infiltration. They don't fix water sources (foundation seepage, plumbing leaks, roof leaks). If your basement floods because of foundation drainage, the dehumidifier runs continuously, costs $50/month in electricity, and the floor still gets wet. Diagnose source FIRST.",
      "amountSaved": {
        "low": 200,
        "high": 320
      },
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "EPA basement moisture diagnosis guidance"
      ]
    },
    {
      "id": "skip_cheap_moisture_meter_moisture",
      "type": "wrong_version",
      "title": "Cheap moisture meters with poor accuracy",
      "marketingPitch": "\"Detects all moisture problems.\"",
      "realReason": "$10-20 meters give inconsistent readings. They produce numbers that look authoritative but mislead diagnosis — you might 'fix' a wall that wasn't actually wet, or miss one that is. The General Tools MMD4E at $40 is the right tier.",
      "amountSaved": {
        "low": 10,
        "high": 25
      },
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "Moisture meter accuracy testing"
      ]
    },
    {
      "id": "skip_single_hygrometer_whole_house",
      "type": "wrong_version",
      "title": "Single hygrometer for whole-house monitoring",
      "marketingPitch": "One sensor, whole-house view.",
      "realReason": "Vermont basements often run 20-30% higher humidity than upstairs. One sensor in the living room misses the basement problem entirely. The 3-pack covers basement, primary bath, and utility room — the actual moisture-prone zones.",
      "amountSaved": {
        "low": 20,
        "high": 40
      },
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "Whole-house humidity zone variance data"
      ]
    },
    {
      "id": "skip_diy_mold_test_visible_mold",
      "type": "wrong_version",
      "title": "DIY mold test kits as substitute for pro inspection",
      "marketingPitch": "Test for mold yourself, save money on inspection.",
      "realReason": "DIY kits screen — they identify if mold is present. They don't diagnose hidden mold or quantify severity. With visible mold over 10 sq ft, you need pro inspection. The DIY kit is the wrong tool when you already know you have a problem.",
      "amountSaved": {
        "low": 250,
        "high": 600
      },
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "EPA mold remediation guidance"
      ]
    },
    {
      "id": "skip_ozone_machines",
      "type": "wrong_category",
      "title": "Ozone machines for odor / mold removal",
      "realReason": "Ozone machines are sold for odor removal and 'mold remediation'. Ozone is a respiratory irritant; the EPA explicitly warns against using ozone for residential indoor air. They mask odors temporarily and can damage plants, rubber, and electronics. Use activated charcoal and ventilation instead.",
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "EPA ozone generator guidance"
      ]
    },
    {
      "id": "skip_mold_bomb_foggers",
      "type": "wrong_category",
      "title": "Mold-bomb fogger products",
      "realReason": "Marketed for DIY mold remediation. Foggers spread chemicals throughout the room without addressing the underlying moisture source. The mold returns once moisture conditions return. Real mold remediation requires removing affected materials and fixing the moisture source — not fogging.",
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "EPA mold remediation guidance — fogger limitations"
      ]
    },
    {
      "id": "skip_scented_plug_ins",
      "type": "wrong_category",
      "title": "Scented plug-ins / sprays / candles to mask musty smell",
      "realReason": "Plug-ins, sprays, and candles mask smells while the underlying moisture problem worsens. You're paying $5-15/month for products that hide the problem. The dehumidifier + charcoal solution is permanent; the masking products are perpetual cost.",
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "Air freshener vs root-cause solutions"
      ]
    },
    {
      "id": "skip_damprid_for_basement",
      "type": "wrong_category",
      "title": "Tiny DampRid packs for whole-basement use",
      "realReason": "DampRid (calcium chloride desiccant) works for closets, RVs, and small enclosed spaces. The 12 oz tubs sold for $5-7 absorb a few ounces of water before saturating. For a Vermont basement that processes gallons of moisture per day, you'd need 50+ tubs replaced weekly. Use a real dehumidifier.",
      "appliesToScope": [
        "home_moisture_control"
      ],
      "citations": [
        "DampRid capacity specifications vs basement humidity loads"
      ]
    }
  ],
  "scenarioDefaults": {
    "just_starting": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    },
    "already_have_basics": {
      "selectedTier": "sweet_spot",
      "alreadyHave": [
        "has_dehumidifier",
        "has_hygrometer"
      ]
    },
    "tight_budget": {
      "selectedTier": "budget",
      "alreadyHave": []
    },
    "absentee_owner": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    }
  },
  "smartCartPromise": "Spend $50-$400 to catch moisture problems before they become smell, mold, or repair issues.",
  "primaryCustomerPain": "Vermont second homes and basements develop musty smells over winter. By the time you smell it, mold has typically been growing 2-3 weeks. Catching the moisture trend before the smell prevents the mold and the smell.",
  "valueProposition": "A $150 monitoring + dehumidifier kit prevents the most common second-home complaint (musty smell) and the underlying problem (mold growth that costs $1,000-$10,000+ to remediate).",
  "routeOutRules": [
    {
      "condition": "has_visible_mold",
      "destination": "small_pro",
      "reason": "Visible mold (more than ~10 sq ft) is a remediation problem, not a moisture-control problem. Get a mold inspection. Smart Cart cannot solve active mold."
    },
    {
      "condition": "has_visible_water_intrusion",
      "destination": "small_pro",
      "reason": "Active water intrusion (foundation, roof, plumbing) is the underlying issue. Dehumidifiers treat ambient moisture; they don't fix water sources. Diagnose and fix the source first."
    }
  ]
}
