// V7.2.5 — Trimmed outdoor_freeze_prevention scope catalog.
//
// Generated by scripts/ingest-catalog.ts from
// scripts/source-catalogs/outdoor-freeze-prevention.ts.
// Editorial layer only. Product data lives in
// src/content/smart-cart/universe.ts.

import type { ScopeCatalog } from '@/lib/smart-cart-model'

export const OUTDOOR_FREEZE_PREVENTION: ScopeCatalog = {
  "topic": "outdoor",
  "scopeVariantId": "outdoor_freeze_prevention",
  "scenarios": [
    "just_starting",
    "already_have_basics",
    "tight_budget",
    "absentee_owner"
  ],
  "slots": [
    {
      "slotId": "freeze_leak_sensor",
      "slotLabel": "Water leak detector (WiFi or LoRa)",
      "slotKind": "core",
      "conditionalOn": [
        "has_leak_detection"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "leak_detector"
          ],
          "mustHaveRoles": [
            "sensor"
          ],
          "excludeAlreadyHaveFlag": "has_leak_detection",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "leak_detector"
          ],
          "mustHaveRoles": [
            "sensor"
          ],
          "excludeAlreadyHaveFlag": "has_leak_detection",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "leak_detector"
          ],
          "mustHaveRoles": [
            "sensor"
          ],
          "excludeAlreadyHaveFlag": "has_leak_detection",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Govee WiFi 3-pack covers the three highest-risk locations (water heater, washing machine, under-kitchen-sink) at the price of one good plumber visit. Setup is 15 minutes. The 5-year battery means you do not have to think about it again until 2031.",
      "whyNotCheaper": "The audible-only Govee 5-pack is fine if you live in the house full-time and will hear the alarm. For a Vermont second home where you visit monthly, an audible alarm might run for 2 weeks before you hear it. The real product is detection that reaches your phone — that requires WiFi.",
      "whyNotPremium": "YoLink LoRa is the right call IF (a) your WiFi is unreliable, (b) the property is large enough that sensors are far from the router, or (c) you want cellular fallback during power outages. For most Vermont second homes with decent WiFi, the Govee WiFi delivers 95% of the value at half the price.",
      "contextNote": "Govee gateway only pairs with H5054 sensors. If you grow the system later, you must use the same generation. Confirm the bundled gateway and sensors match before opening.",
      "warnings": [
        "Govee gateway requires 2.4GHz WiFi. Many newer routers default to 5GHz only or merge bands; you may need to enable a separate 2.4GHz network.",
        "Place sensors at floor level or in pans, not on countertops. Probes need direct water contact.",
        "Test the alert path (intentionally trigger a sensor) once a year. App notifications can silently break after firmware updates."
      ],
      "citations": [
        "Govee H5054 + H5040 gateway product documentation",
        "YoLink LoRa product specs (1/4 mile open-air range)",
        "Insurance industry data on water damage as the most common non-weather homeowner claim"
      ],
      "slotPurpose": "Detect a leak within seconds, before it becomes a flood.",
      "whyItMatters": "A pinhole leak in a copper pipe at 1 gallon per minute fills a finished basement in 12 hours. With detection, the same leak is a $50 plumber call. Without it, $15,000+ in damage and mold remediation.",
      "commonMistake": "Buying audible-only alarms for an absentee property. If no one is there to hear the alarm, the alarm is theater.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "smart_shutoff_valve",
        "reason": "You already detect leaks. The next-step gap is automatic shutoff so the leak stops without you driving 2 hours to manually close the main valve."
      },
      "whenToSkip": [
        "Property has municipal water with auto-shutoff at the meter (rare in rural Vermont)",
        "Property is fully drained for winter (no water in pipes)"
      ],
      "routeOutOfSmartCartIf": [
        {
          "condition": "has_visible_active_leak",
          "destination": "small_pro",
          "reason": "Stop shopping. Call a plumber. Sensors are for prevention, not for diagnosing an active leak."
        }
      ]
    },
    {
      "slotId": "freeze_pipe_insulation",
      "slotLabel": "Pipe insulation foam (6 ft tubes)",
      "slotKind": "core",
      "conditionalOn": [
        "has_pipe_insulation",
        "pipes_in_conditioned_space_only"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "pipe_insulation"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_pipe_insulation",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "pipe_insulation"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_pipe_insulation",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "pipe_insulation"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_pipe_insulation",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Frost King 3/4\" 4-pack is the most common Vermont residential supply line size. Four 3-foot pieces covers ~12 feet of pipe — enough for the typical run from main shutoff to water heater plus exposed runs to outside hose bibs.",
      "whyNotCheaper": "Single 6-foot tubes are fine for one pipe run. The 4-pack saves ~30% per foot if you have multiple runs, which most Vermont homes do.",
      "whyNotPremium": "1\" rubber insulation is the right call for pipes in unconditioned crawlspaces or near outside walls. For pipes inside the conditioned basement envelope, the foam tubes are sufficient and easier to install. Save the rubber for the spots that actually need it.",
      "contextNote": "Vermont frost line is approximately 48 inches in northern counties. Supply lines in unheated crawlspaces have higher freeze risk than those running through finished basements.",
      "warnings": [
        "Measure pipe outer diameter (OD), not nominal. 1/2\" copper has a 5/8\" OD; the insulation sleeve must match the OD, not the nominal.",
        "Pipe insulation alone is not enough for unconditioned spaces below 20°F. You need heat tape too in those locations."
      ],
      "citations": [
        "Frost King Amazon listing (B000BQLSBI, B07XLQ5TPG, B003A0YX82)",
        "EPA pipe insulation guidance for cold-climate residential",
        "NFPA freeze prevention recommendations"
      ],
      "slotPurpose": "Slow heat loss on supply pipes so they take longer to reach freezing temperature.",
      "whyItMatters": "Pipe insulation does not prevent freezing on its own. It buys hours of time before a pipe freezes. In a conditioned basement that briefly drops to 35°F during a power outage, insulation can mean the difference between cold pipes and burst pipes.",
      "commonMistake": "Buying pipe insulation without measuring pipe diameter first. 1/2\" copper, 3/4\" copper, and 1\" iron pipe each take a different size sleeve. Wrong size means gaps.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "pipe_freeze_alarm",
        "reason": "Insulation slows freezing. A freeze alarm tells you when a pipe is approaching freezing temperature so you can act before the pipe bursts."
      },
      "whenToSkip": [
        "All supply pipes are inside conditioned, heated space and the heating system is reliable",
        "Property is fully winterized (drained) for the season"
      ]
    },
    {
      "slotId": "freeze_heat_tape",
      "slotLabel": "Self-regulating heat tape with built-in thermostat",
      "slotKind": "core",
      "conditionalOn": [
        "has_heat_tape",
        "no_unconditioned_pipes"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "heat_tape"
          ],
          "mustHaveRoles": [
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_heat_tape",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "heat_tape"
          ],
          "mustHaveRoles": [
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_heat_tape",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "heat_tape"
          ],
          "mustHaveRoles": [
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_heat_tape",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Frost King self-regulating cable adjusts output based on pipe temperature, eliminating the constant-on fire risk. Built-in thermostat means no separate outlet box. UL listed. The plug-in design lets you install without an electrician for a single pipe run.",
      "whyNotCheaper": "Constant-wattage heat cables without thermostats are a known fire risk per the NFPA. The $15 savings is not worth the risk to a home you are not in to monitor.",
      "whyNotPremium": "Pro-grade kits with hardwired installation are the right call for permanent solutions on long pipe runs (>20 ft) or where outlets are not available. For most single exposed pipe runs, the plug-in self-regulating cable does the same job.",
      "contextNote": "Heat tape is layered ON TOP of pipe insulation, with insulation OUTSIDE. Bare pipe → heat tape spiraled on → insulation sleeve → done. Skipping the insulation step doubles the energy cost.",
      "warnings": [
        "NEVER use heat tape without a thermostat. Constant-on heat tape is a documented fire risk.",
        "NEVER overlap heat tape on itself (creates hot spots).",
        "Inspect heat tape annually for cracks or damage. Replace immediately if damaged.",
        "Most heat tape is rated for 3-5 years of use. Plan for replacement."
      ],
      "citations": [
        "NFPA fire risk documentation on heat tape",
        "Frost King product line documentation",
        "Pentair / Raychem self-regulating heat cable specifications"
      ],
      "slotPurpose": "Actively heat pipes in unconditioned spaces to prevent freezing during deep cold.",
      "whyItMatters": "For pipes in unheated crawlspaces, attics, or runs along exterior walls, insulation alone is insufficient when ambient temperature drops below 15°F for sustained periods. Heat tape is the active prevention layer.",
      "commonMistake": "Buying constant-wattage heat tape WITHOUT a thermostat. These cables run continuously when plugged in and are a documented fire-risk source. Always self-regulating, always with thermostat — no exception.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "pipe_freeze_alarm",
        "reason": "You have prevention. Add detection (a freeze alarm) so you know if the heat tape fails or the breaker trips."
      },
      "whenToSkip": [
        "No pipes run through unheated spaces (entirely in conditioned basement)",
        "Property is winterized (drained) and not in use during freeze risk",
        "Pipes are PEX (more freeze-tolerant than copper, though still freeze-vulnerable)"
      ],
      "routeOutOfSmartCartIf": [
        {
          "condition": "permanent_install_long_run",
          "destination": "small_pro",
          "reason": "For permanent installations on pipe runs longer than 20 feet, or where the cable needs to be hardwired, hire a plumber or electrician. Heat tape is fire-risk if installed incorrectly."
        }
      ]
    },
    {
      "slotId": "freeze_smart_thermostat",
      "slotLabel": "Smart thermostat with remote temperature alerts",
      "slotKind": "core",
      "conditionalOn": [
        "has_smart_thermostat",
        "incompatible_hvac_system"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "smart_thermostat"
          ],
          "mustHaveRoles": [
            "monitor",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_smart_thermostat",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "smart_thermostat"
          ],
          "mustHaveRoles": [
            "monitor",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_smart_thermostat",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "smart_thermostat"
          ],
          "mustHaveRoles": [
            "monitor",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_smart_thermostat",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Honeywell T9 has the broadest HVAC compatibility in the smart-thermostat category and the alert system is reliable. The geofencing automatically holds a higher minimum when you're not home but you're driving toward the property. App-based override is essential for Vermont second-home owners.",
      "whyNotCheaper": "Non-smart programmable thermostats are fine if you live in the house full-time and will see the temperature display daily. For a property visited monthly, you cannot react to a problem you cannot see.",
      "whyNotPremium": "Ecobee Premium adds room sensors and voice control. Both useful in a primary residence with multiple zones. For a single-zone Vermont second home where the question is just 'is the heat working?', the Honeywell T9 answers that question for $80 less.",
      "contextNote": "Set the away minimum no lower than 50°F for properties with water in pipes. 50°F gives ~6 hours of buffer before pipes reach freeze risk if heat fails. Lower setpoints save energy but reduce the buffer window for response.",
      "warnings": [
        "Verify HVAC compatibility before buying. Honeywell and Ecobee both publish compatibility checkers.",
        "C-wire required for most smart thermostats. If your existing thermostat uses only 2 wires, you may need an electrician to add a C-wire.",
        "WiFi outage = no alerts. Pair with a freeze alarm that has cellular backup if reliability is critical."
      ],
      "citations": [
        "Honeywell Home T9 product documentation",
        "Ecobee Premium product documentation",
        "Vermont residential heating systems compatibility data"
      ],
      "slotPurpose": "Maintain a minimum temperature setpoint when away, and alert you if the house starts cooling unexpectedly.",
      "whyItMatters": "Without remote alerts, the first sign of a heat failure in an absentee home is often a frozen pipe. A smart thermostat that tells you the house is at 38°F and dropping is a $150 spend that can prevent a $15,000 repair.",
      "commonMistake": "Buying a smart thermostat without verifying HVAC compatibility. Some Vermont second homes have older oil systems, propane heaters, or zoned hydronic systems that don't work with modern smart thermostats — or work but lose features. Check compatibility BEFORE buying.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "leak_detector",
        "reason": "Smart thermostat tells you the heat is working. A leak detector tells you whether the pipes are still intact. Together they cover the two most common failure modes."
      },
      "whenToSkip": [
        "HVAC system incompatible with smart thermostats (verified)",
        "No reliable WiFi at the property"
      ],
      "routeOutOfSmartCartIf": [
        {
          "condition": "incompatible_hvac_system",
          "destination": "verify_first",
          "reason": "Smart thermostats require specific HVAC wiring. Verify compatibility first via the manufacturer's compatibility tool. If incompatible, route to a different solution like a freeze alarm."
        }
      ]
    },
    {
      "slotId": "freeze_hose_bib_cover",
      "slotLabel": "Outdoor hose bib (faucet) cover",
      "slotKind": "core",
      "conditionalOn": [
        "has_hose_bib_covers",
        "no_outdoor_hose_bibs"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "hose_bib_cover"
          ],
          "mustHaveRoles": [
            "accessory",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_hose_bib_covers",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "hose_bib_cover"
          ],
          "mustHaveRoles": [
            "accessory",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_hose_bib_covers",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "hose_bib_cover"
          ],
          "mustHaveRoles": [
            "accessory",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_hose_bib_covers",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Frost King thermal cover works in real Vermont conditions (down to ~10°F) with the supply shut off and bib drained. The 2-pack covers front and back yard bibs in one purchase. Hard shell prevents critter damage that foam covers don't.",
      "whyNotCheaper": "Foam covers fail below 15°F and are easily torn off by wind or critters. They are appropriate for moderate climates, not Vermont winters.",
      "whyNotPremium": "A frost-proof sillcock is the permanent solution and worth doing on next renovation. For an existing home in October, the cover is the right tactical move; the sillcock replacement is a spring project.",
      "contextNote": "ALWAYS shut off and drain the outdoor faucet before installing the cover. The cover insulates; it does not heat. Water in the bib will still freeze if temperatures stay below 20°F for sustained periods.",
      "warnings": [
        "Disconnect garden hoses before winter. Hoses left connected trap water in the bib that cannot drain, defeating the cover.",
        "Some older sillcocks have an inside shutoff with a separate drain plug. Find both before assuming the bib is drained."
      ],
      "citations": [
        "Frost King hose bib cover documentation",
        "Vermont residential plumbing freeze data"
      ],
      "slotPurpose": "Insulate the outdoor faucet to prevent water in the bib from freezing and pushing back into the supply line.",
      "whyItMatters": "An outdoor faucet that freezes can crack the supply line behind the wall, causing the leak to appear inside the house when temperatures rise. The cover does not freeze-proof — it slows freezing and gives you time to drain the bib.",
      "commonMistake": "Leaving covers off a hose bib that has water in the supply line. Even with a cover, you should disconnect the hose and shut off the supply valve inside before freezing weather.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "shutoff_labels",
        "reason": "You have hose bibs covered. The next-step gap is labeling all shutoffs (water main, water heater, individual bib supply valves) so anyone in the house during an emergency knows where to turn things off."
      },
      "whenToSkip": [
        "No outdoor hose bibs",
        "Property has frost-proof sillcocks installed (modern construction)",
        "Property is fully winterized (water shut off at main)"
      ]
    },
    {
      "slotId": "freeze_draft_sealing",
      "slotLabel": "Door and window draft sealing kit",
      "slotKind": "addon",
      "conditionalOn": [
        "has_weatherstripping_recent",
        "has_no_drafts"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "draft_sealer"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_weatherstripping_recent",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "draft_sealer"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_weatherstripping_recent",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "draft_sealer"
          ],
          "mustHaveRoles": [
            "consumable_material",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_weatherstripping_recent",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Kit includes V-strip (lasts longer than foam) plus door sweep plus window sill draft stoppers — the three highest-leverage draft sources in a typical Vermont home.",
      "whyNotCheaper": "Foam weatherstripping is fine for windows that don't open often. For doors used daily, the foam compresses within months. The kit's V-strip is the right material for high-use locations.",
      "whyNotPremium": "Silicone bulb seal is the gold standard but installation is more demanding. For a typical seasonal-home homeowner, the V-strip kit covers 90% of draft sources at half the price.",
      "citations": [
        "M-D Building Products and Frost King weatherstripping product lines",
        "DOE residential weatherstripping guidance"
      ],
      "slotPurpose": "Reduce cold air infiltration so the heating system isn't fighting drafts and the freeze-vulnerable spots stay warmer.",
      "whyItMatters": "Drafts increase heating cost and create cold pockets near pipes in exterior walls. Even modest weatherstripping reduces freeze risk and saves 5-15% on heating cost.",
      "commonMistake": "Foam weatherstripping on door jambs that get heavy use. The foam compresses permanently within 1-2 seasons and stops sealing. V-strip vinyl lasts 5-10 years."
    },
    {
      "slotId": "freeze_shutoff_labels",
      "slotLabel": "Utility shutoff labeling kit",
      "slotKind": "core",
      "conditionalOn": [
        "has_shutoff_labels"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "shutoff_labels"
          ],
          "mustHaveRoles": [
            "document_aid",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_shutoff_labels",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "An $8 spend that pays back the first time anyone needs to shut off water and isn't sure which valve to turn. Especially valuable for absentee homes where a neighbor or property manager may need to act on your behalf.",
      "whyNotCheaper": "Hand-written tags work but fade and fall off. Adhesive printed labels last 5+ years.",
      "whyNotPremium": "Engraved brass tags exist for $3-5 each but the value beyond plastic adhesive labels is minimal.",
      "contextNote": "Pair this with a printed shutoff diagram taped near the main panel showing each labeled valve's location. The labels are useless if no one can find the basement utility room.",
      "citations": [
        "NFPA fire and safety labeling standards",
        "Insurance industry water damage minimization guidance"
      ],
      "slotPurpose": "Make it possible for anyone in the house — guest, contractor, neighbor — to find and operate critical shutoffs in an emergency.",
      "whyItMatters": "When a pipe bursts at 2am, the first 5 minutes of finding the right valve makes the difference between $200 and $5,000 of damage. Unlabeled valves cost time you don't have.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "emergency_docs",
        "reason": "Labels are in place. The next-step gap is a printed emergency contact sheet — plumber, electrician, neighbor with key, insurance — kept near the labels."
      }
    },
    {
      "slotId": "freeze_smart_shutoff_valve",
      "slotLabel": "Automatic water shutoff valve",
      "slotKind": "addon",
      "conditionalOn": [
        "has_smart_shutoff",
        "water_already_drained"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "smart_shutoff_valve"
          ],
          "mustHaveRoles": [
            "hardware"
          ],
          "excludeAlreadyHaveFlag": "has_smart_shutoff",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "smart_shutoff_valve"
          ],
          "mustHaveRoles": [
            "hardware"
          ],
          "excludeAlreadyHaveFlag": "has_smart_shutoff",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Moen Flo is the verified residential auto-shutoff. Pairs with leak sensors, learns your home's normal water-use patterns, and shuts off on anomaly. ~$500 installed for the valve plus pro install. Real insurance discount qualifying — many insurers offer 5-15% premium reduction.",
      "whyNotCheaper": "There is no real cheaper tier. Either you have leak detection that requires you to act, or you have automatic shutoff that acts for you. Half-measures here are not useful.",
      "whyNotPremium": "YoLink is a strong alternative if your WiFi is unreliable or you already have YoLink leak sensors. For most Vermont second homes with reasonable WiFi, Moen Flo is the better-supported option.",
      "contextNote": "Almost always requires professional plumber install. Budget $200-400 for labor in addition to the device cost. Verify with your insurance carrier whether installation qualifies for premium discount BEFORE buying.",
      "warnings": [
        "Professional plumber install is the right call. DIY install on a main supply line is a real risk.",
        "Verify your home's water main valve is accessible and can be shut off easily before scheduling install."
      ],
      "citations": [
        "Moen Flo product documentation",
        "YoLink smart water shutoff specifications",
        "Insurance industry data on auto-shutoff premium discounts"
      ],
      "slotPurpose": "Automatically shut off the water supply when a leak is detected, without requiring you to be present.",
      "whyItMatters": "Detection alone tells you a leak happened. Automatic shutoff stops the leak. For a property visited monthly, this is the difference between a 2-hour leak and a 30-day leak.",
      "commonMistake": "Buying a smart shutoff valve and installing it yourself without plumbing experience. These valves go on the main supply line. A botched install is a worse leak than the one you're trying to prevent.",
      "routeOutOfSmartCartIf": [
        {
          "condition": "water_already_drained",
          "destination": "verify_first",
          "reason": "If you've already drained the water system for winter, an auto-shutoff valve is unnecessary until spring opening. Reconsider in April."
        },
        {
          "condition": "no_main_shutoff_access",
          "destination": "small_pro",
          "reason": "If your home's main shutoff is buried, frozen, or inaccessible, fix that problem first via a plumber visit. Adding a smart shutoff to an inaccessible main line creates new failure modes."
        }
      ]
    },
    {
      "slotId": "freeze_alarm_non_wifi",
      "slotLabel": "Cellular or phone-line freeze alarm (no WiFi)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_freeze_alarm",
        "has_reliable_wifi"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "pipe_freeze_alarm"
          ],
          "mustHaveRoles": [
            "sensor",
            "monitor"
          ],
          "excludeAlreadyHaveFlag": "has_freeze_alarm",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "For homes without WiFi, this is the only category of freeze monitoring that actually works. Subscription cost ($60-150/year) is real, but it's the difference between getting an alert and not getting an alert.",
      "whyNotCheaper": "There is no real cheaper option for cellular monitoring. The hardware is bundled with the subscription model.",
      "whyNotPremium": "Higher-tier monitoring services exist (with multiple sensors, redundant alerts, professional monitoring) for $300-500/year. Worth considering for very high-value properties or art/wine collection storage.",
      "contextNote": "Subscription is mandatory for cellular service. Budget $5-12/month ongoing in addition to hardware cost. Some services offer 1-year prepay discounts.",
      "warnings": [
        "Subscription must be renewed. A lapsed subscription means a silent sensor.",
        "Cellular signal must be checkable at the property before purchase. Some Vermont valleys have no cellular coverage either."
      ],
      "citations": [
        "Marcell and Temp Stick product documentation",
        "Cellular monitoring service comparisons"
      ],
      "slotPurpose": "Get freeze alerts on properties without reliable WiFi.",
      "whyItMatters": "Many rural Vermont second homes have unreliable or no WiFi. WiFi-dependent sensors fail silently when the router reboots or the ISP drops. A cellular freeze alarm has independent connectivity.",
      "commonMistake": "Relying on WiFi sensors at a property where you've personally experienced WiFi outages. If you've ever lost internet at the cabin, your sensors will lose internet too — at the worst possible moment.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "leak_detector",
        "reason": "You have temperature monitoring. The next-step gap is leak detection. Heat working is necessary but not sufficient — pipes can still leak from other causes."
      }
    }
  ],
  "skipList": [
    {
      "id": "skip_constant_wattage_heat_tape",
      "type": "wrong_version",
      "title": "Constant-wattage heat tape without thermostat",
      "marketingPitch": "Cheaper heat cable, just plug it in.",
      "realReason": "Documented fire risk per the NFPA. Constant-wattage cables run continuously when plugged in and have started home fires when overheated under insulation. Always self-regulating, always with a thermostat — no exceptions. The $15 saved is not worth a house fire risk in a property you're not present to monitor.",
      "amountSaved": {
        "low": 15,
        "high": 25
      },
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "NFPA fire risk documentation on heat cables"
      ]
    },
    {
      "id": "skip_audible_only_alarms_for_absentee",
      "type": "wrong_version",
      "title": "Audible-only leak alarms for an absentee property",
      "marketingPitch": "100dB alarm — loud enough to hear from anywhere in the house.",
      "realReason": "If no one is in the house to hear it, the alarm is theater. For a Vermont second home visited monthly, an audible-only alarm running continuously for 2 weeks before discovery does no good. The $40 saved by skipping WiFi is the wrong save — this is precisely the slot where WiFi matters.",
      "amountSaved": {
        "low": 30,
        "high": 45
      },
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Govee H5054 product documentation"
      ]
    },
    {
      "id": "skip_smart_thermostat_no_compatibility_check",
      "type": "wrong_version",
      "title": "Smart thermostat without verifying HVAC compatibility",
      "marketingPitch": "Universal compatibility, works with any system.",
      "realReason": "Smart thermostats fail to install or lose features on many older Vermont heating systems (oil boilers, hydronic baseboards, propane heaters with proprietary controls). The $150 thermostat that won't work is more expensive than the $30 programmable that does. Verify with the manufacturer's compatibility tool before buying.",
      "amountSaved": {
        "low": 100,
        "high": 180
      },
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Honeywell Home and Ecobee compatibility checker tools"
      ]
    },
    {
      "id": "skip_thin_pipe_insulation_unconditioned",
      "type": "wrong_version",
      "title": "3/8\" wall foam insulation in unconditioned crawlspaces",
      "marketingPitch": "Standard pipe insulation for any application.",
      "realReason": "Thin foam insulation is for pipes in conditioned space (R-value ~3). In an unheated crawlspace at 0°F, the foam buys minutes, not hours. Use 1/2\" wall rubber insulation (R-value ~5) plus heat tape for unconditioned spaces. The $5 saved is meaningless if the pipe still freezes.",
      "amountSaved": {
        "low": 5,
        "high": 12
      },
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Frost King product line documentation by application"
      ]
    },
    {
      "id": "skip_foam_hose_bib_cover_vermont",
      "type": "wrong_version",
      "title": "Foam hose bib covers in Vermont",
      "marketingPitch": "Slip-on foam cover, easy install.",
      "realReason": "Foam covers fail below 15°F and are easily torn off by wind or critters. Effective for moderate climates. In Vermont winters with sustained cold and wildlife pressure, the hard-shell thermal cover is the right tier. The $5 saved makes the cover worse than no cover.",
      "amountSaved": {
        "low": 5,
        "high": 10
      },
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Cold-climate hose bib cover testing"
      ]
    },
    {
      "id": "skip_propane_heater_winterization",
      "type": "wrong_category",
      "title": "Propane patio heaters marketed as winterization",
      "realReason": "Propane patio heaters are outdoor seasonal heaters for entertaining. They are not freeze prevention. They cannot be safely operated indoors (CO risk), and outdoors they don't address pipe freezing inside the house. Skip.",
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "CDC carbon monoxide guidance for indoor propane use"
      ]
    },
    {
      "id": "skip_pipe_heating_alone_for_unconditioned",
      "type": "wrong_category",
      "title": "Pipe insulation alone for pipes in unconditioned crawlspaces",
      "realReason": "Insulation slows freezing; it does not prevent it. For a crawlspace below 20°F for sustained periods, pipe insulation buys hours, not days. You need heat tape WITH insulation, not insulation as a standalone solution. Buying insulation for an unconditioned space and stopping there is a partial solution that fails on the worst nights.",
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Pipe insulation R-value testing in cold climates"
      ]
    },
    {
      "id": "skip_smart_lighting_as_security",
      "type": "wrong_category",
      "title": "Smart lighting marketed as \"occupied appearance\" for absentee homes",
      "realReason": "Marketed as security/freeze-prevention bundle. Smart lighting that turns on lights doesn't prevent freezing or detect leaks. Spend the $200 on actual freeze prevention — leak sensors, smart thermostat, freeze alarm — not on lights that look like someone is home.",
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Insurance industry data on absentee home loss prevention"
      ]
    },
    {
      "id": "skip_universal_pipe_insulation_kit",
      "type": "wrong_category",
      "title": "Pre-bundled \"complete pipe insulation kit\" with multiple sizes",
      "realReason": "Kits include sizes you don't need (1/4\", 5/8\", 1.25\") for $50+. Most homes have one or two pipe sizes — typically 1/2\" or 3/4\" copper. Buy the right size in bulk for $20. The kit's convenience pricing is real but you're paying for foam tubes you'll throw away.",
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Per-size vs kit pricing analysis"
      ]
    },
    {
      "id": "skip_decorative_pipe_covers",
      "type": "wrong_category",
      "title": "Decorative wood or plastic pipe covers",
      "realReason": "Marketed for finished basements as visual concealment of pipe runs. They have R-value near zero. If your goal is freeze prevention, the decorative cover does nothing. If your goal is aesthetics, do the foam insulation underneath the decorative cover — but don't substitute one for the other.",
      "appliesToScope": [
        "outdoor_freeze_prevention"
      ],
      "citations": [
        "Pipe insulation vs cosmetic cover R-value comparison"
      ]
    }
  ],
  "scenarioDefaults": {
    "just_starting": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    },
    "already_have_basics": {
      "selectedTier": "sweet_spot",
      "alreadyHave": [
        "has_pipe_insulation",
        "has_shutoff_labels"
      ]
    },
    "tight_budget": {
      "selectedTier": "budget",
      "alreadyHave": []
    },
    "absentee_owner": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    }
  },
  "smartCartPromise": "Spend $100-$500 to reduce risk of frozen pipes, water damage, and emergency calls.",
  "primaryCustomerPain": "A burst pipe in an unoccupied home can flood for days before anyone knows. Vermont second-home owners are the highest-risk segment.",
  "valueProposition": "A $400 spend on detection and prevention can defer or avoid a $5,000-$25,000 water damage repair, plus eliminate the cost of an emergency plumber visit (which doesn't exist in rural Vermont in January anyway).",
  "routeOutRules": [
    {
      "condition": "has_visible_water_damage",
      "destination": "small_pro",
      "reason": "Active or recent water damage means the prevention window has already closed. Get the damage assessed by a plumber before adding sensors."
    },
    {
      "condition": "has_unconditioned_crawlspace",
      "destination": "verify_first",
      "reason": "Pipe insulation in an unconditioned crawlspace below 20°F is not enough on its own. You need either heated tape, a freeze alarm, or to drain the system. Get a verification visit first."
    },
    {
      "condition": "planning_long_absence_no_wifi",
      "destination": "verify_first",
      "reason": "Without reliable WiFi or cellular, smart sensors won't reach you. Consider draining the water system entirely, or installing a cellular hub before sensors."
    }
  ],
  "seasonalUrgency": {
    "season": "pre_winter",
    "deadline": "11-01",
    "label": "Best by November 1 — typical Vermont first hard freeze window. Ship times in October are 2-5 days; in late November they slip."
  }
}
