// V7.2.5 — Trimmed outdoor_seasonal_opening scope catalog.
//
// Generated by scripts/ingest-catalog.ts from
// scripts/source-catalogs/outdoor-seasonal-opening.ts.
// Editorial layer only. Product data lives in
// src/content/smart-cart/universe.ts.

import type { ScopeCatalog } from '@/lib/smart-cart-model'

export const OUTDOOR_SEASONAL_OPENING: ScopeCatalog = {
  "topic": "outdoor",
  "scopeVariantId": "outdoor_seasonal_opening",
  "scenarios": [
    "just_starting",
    "already_have_basics",
    "tight_budget",
    "absentee_owner"
  ],
  "slots": [
    {
      "slotId": "opening_water_test_kit",
      "slotLabel": "Drinking water test kit",
      "slotKind": "core",
      "conditionalOn": [
        "has_recent_water_test",
        "on_municipal_water"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "water_test_kit"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_water_test",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "water_test_kit"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_water_test",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "water_test_kit"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_recent_water_test",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Tap Score Essential covers Vermont's specific concerns (radon, arsenic, bacteria) at a price comparable to a single bottled water case for the season. The interpretation guidance is the real value — raw results without context are noise.",
      "whyNotCheaper": "Strip tests are useful for screening (is the chlorine in your municipal water in range?). They are not reliable for bacteria detection or low-concentration metals. For an annual well water test, the lab analysis is worth the price difference.",
      "whyNotPremium": "The Advanced panel makes sense for a new property purchase, after a known contamination event, or once every 5 years for full re-baselining. Annual routine testing is well-served by the Essential panel.",
      "contextNote": "Vermont Department of Health recommends annual private well testing for bacteria and every 5 years for chemistry. State data on regional contamination is publicly available and worth reviewing before choosing a test panel.",
      "warnings": [
        "Test BEFORE drinking, not after. Same-day results are not available for proper bacteria testing.",
        "Sampling matters. Follow the kit's sampling instructions exactly — improper sampling produces useless results."
      ],
      "citations": [
        "Vermont Department of Health well water testing guidance",
        "Tap Score by SimpleLab product documentation",
        "EPA private well water testing recommendations"
      ],
      "slotPurpose": "Verify the water is safe to drink before pouring coffee on opening day.",
      "whyItMatters": "Wells that sat unused over winter can develop bacterial contamination from low flow. Vermont well water has known background concerns including arsenic in some regions and radon-in-water. Annual testing is the right baseline; opening-day testing is the right timing.",
      "commonMistake": "Skipping the test because the water 'tasted fine last year'. Bacterial contamination has no taste. Test results take 5-10 days for the lab — order it before you arrive so you have a fresh test for the season.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "sediment_filter",
        "reason": "You have a recent test. The next-step gap is filtration matched to your test results — typically a sediment filter for most rural Vermont wells."
      },
      "whenToSkip": [
        "Property is on municipal water (state tests this)",
        "Tested within the last 12 months and results were within range"
      ]
    },
    {
      "slotId": "opening_leak_check",
      "slotLabel": "Leak check kit (manual)",
      "slotKind": "core",
      "conditionalOn": [
        "has_leak_detector_installed"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "pressure_gauge",
            "leak_detector"
          ],
          "mustHaveRoles": [
            "measurement_tool",
            "tool"
          ],
          "excludeAlreadyHaveFlag": "has_leak_detector_installed",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Manual inspection on opening day is the highest-leverage 30 minutes you'll spend. Pressure gauge tells you the supply is correct; dye tablets catch toilet flapper leaks; paper towels under fittings catch joint drips.",
      "whyNotCheaper": "There is no cheaper version. The kit is already cheap.",
      "whyNotPremium": "Smart leak sensors are the better long-term answer (covered in freeze prevention scope). For opening-day, manual inspection is the right tactical move.",
      "contextNote": "Do this BEFORE turning on the water heater or running fixtures. A leak with no water pressure is hidden; a leak after pressure is restored is loud and expensive.",
      "citations": [
        "EPA WaterSense leak detection guide",
        "Toilet dye tablet test methodology"
      ],
      "slotPurpose": "First-day systematic leak inspection. Catch leaks that started over winter before they become visible damage.",
      "whyItMatters": "Slow toilet leaks waste 200+ gallons/day and only become visible when the water bill arrives — months later, after the damage. The dye tablet method takes 10 minutes per toilet and catches leaks that auto-detection sensors won't see.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "leak_detector",
        "reason": "You're past manual inspection — get permanent leak detection sensors so you don't repeat the process every spring."
      }
    },
    {
      "slotId": "opening_filter_replacement",
      "slotLabel": "Whole-house water filter replacement",
      "slotKind": "core",
      "conditionalOn": [
        "has_no_filter_system",
        "replaced_filters_recently"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "filter_replacement"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_no_filter_system",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "filter_replacement"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_no_filter_system",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "filter_replacement"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_no_filter_system",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Pentek 2-pack covers the typical Vermont well system: sediment first (catches silt) followed by carbon (improves taste). Industry-standard quality at retail-direct price.",
      "whyNotCheaper": "Generic filters cost ~$6 each but inconsistent quality. The Pentek 2-pack is the right balance of price and reliability for the typical household.",
      "whyNotPremium": "Big Blue is the right call ONLY if your existing housing is Big Blue. If you have standard 10\" housing, premium media in a smaller size is the better fit.",
      "contextNote": "Measure your filter housing BEFORE ordering. Photograph it next to a ruler. Most homes have either standard 10\" or Big Blue 4.5\"x10\". Mismatches don't seal.",
      "warnings": [
        "Always wear nitrile gloves when handling old cartridges. The accumulated sediment can include bacteria.",
        "Sanitize the housing with a bleach rinse if filters were sitting in standing water through winter."
      ],
      "citations": [
        "Pentek product documentation",
        "EPA Drinking Water filter selection guidance"
      ],
      "slotPurpose": "Replace filter cartridges that have been sitting unused all winter or are reaching end-of-life.",
      "whyItMatters": "Filter cartridges that sit in standing water all winter can grow bacteria. Even if the housing held water without freezing, the media degrades. Spring is the right replacement window.",
      "commonMistake": "Buying filters before checking housing size. Filters come in 10\", 4.5\"x10\", 4.5\"x20\", and various proprietary sizes. Wrong size = filter doesn't seal = water bypasses the filter entirely.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "pressure_gauge",
        "reason": "You've replaced filters. The next-step gap is monitoring pressure across the filter — a pressure gauge catches a clogged filter before it stops flow."
      },
      "whenToSkip": [
        "Property has no whole-house filter system",
        "Filter replaced within last 3 months"
      ]
    },
    {
      "slotId": "opening_cleaning_kit",
      "slotLabel": "Spring cleaning reset kit (consumables)",
      "slotKind": "core",
      "conditionalOn": [
        "has_full_cleaning_supplies"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "cleaning_reset_kit"
          ],
          "mustHaveRoles": [
            "cleaner",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_full_cleaning_supplies",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "cleaning_reset_kit"
          ],
          "mustHaveRoles": [
            "cleaner",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_full_cleaning_supplies",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Microfiber + non-toxic cleaners do better on second-home surfaces (often older finishes that don't tolerate harsh chemistry). Bleach for grout and shower; gentler products for everywhere else.",
      "whyNotCheaper": "Generic cleaning kits include items you may already have. If buckets and gloves are at the property, consumables-only is the right answer.",
      "whyNotPremium": "Premium cleaning service kits ($150+) are for daily-use second homes (Airbnb scenarios). For a personal weekend home, the consumables kit covers actual cleaning need.",
      "contextNote": "Open windows during first cleaning. Vermont second homes that sat closed for months have stale-air smells that ventilation alone won't clear — but ventilation is required for many cleaners.",
      "citations": [
        "CDC mold cleanup guidance",
        "Method, Mrs. Meyer's product documentation"
      ],
      "slotPurpose": "Reset all surfaces, especially in bathrooms and kitchen, after months of unused space.",
      "whyItMatters": "Mold and mildew develop in unused bathrooms over winter. The first-day clean prevents these from spreading and prevents the smell that makes guests uncomfortable on day one.",
      "commonMistake": "Buying full cleaning supply kits when only consumable refills are needed. If your second home already has buckets, mops, and gloves stored, you only need the consumables — bleach, microfiber, all-purpose cleaner.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "odor_absorber",
        "reason": "You have cleaning supplies. The next-step gap is moisture/odor control — DampRid, ventilation, or dehumidifier — to prevent the same musty smell next opening."
      }
    },
    {
      "slotId": "opening_dehumidifier",
      "slotLabel": "Dehumidifier (basement or whole-house)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_dehumidifier"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dehumidifier_entry"
          ],
          "mustHaveRoles": [
            "appliance",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_dehumidifier",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dehumidifier_entry"
          ],
          "mustHaveRoles": [
            "appliance",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_dehumidifier",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dehumidifier_entry"
          ],
          "mustHaveRoles": [
            "appliance",
            "preventer"
          ],
          "excludeAlreadyHaveFlag": "has_dehumidifier",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "hOmeLabs 50-pint with continuous drain works well in Vermont basements where you don't want to empty the bucket twice a day. The pump-assisted drain handles uphill discharge to a sink or floor drain.",
      "whyNotCheaper": "30-pint units fail under typical Vermont basement load. They run constantly, fill the bucket twice a day, and burn out within 2-3 seasons. The 50-pint is the right size for most homes.",
      "whyNotPremium": "Whole-house dehumidifiers integrate into HVAC and run quieter, but require pro install and are 5-8x the cost. For most Vermont basements, the 50-pint portable does the job.",
      "contextNote": "Run with continuous drain to a floor drain or pump to a sink. Bucket-only operation is fine for testing but unsustainable for season-long use.",
      "warnings": [
        "Don't use dehumidifier on a damp/wet floor without identifying the water source. The unit will mask drainage problems.",
        "Empty bucket weekly even on continuous drain mode (backup safety)."
      ],
      "citations": [
        "hOmeLabs product documentation",
        "EPA basement moisture control guidance"
      ],
      "slotPurpose": "Reduce ambient moisture in basements, crawlspaces, and seasonal homes to prevent mold growth and protect stored items.",
      "whyItMatters": "Vermont summers are humid. Basements that stay above 60% relative humidity grow mold within weeks. A dehumidifier is the difference between a usable basement and one with permanent musty smell.",
      "commonMistake": "Buying a dehumidifier before identifying water source. If you have water seeping into the basement, a dehumidifier treats the symptom while the actual problem (drainage, foundation, leak) gets worse. Test for source first.",
      "routeOutOfSmartCartIf": [
        {
          "condition": "visible_water_damage",
          "destination": "small_pro",
          "reason": "Visible water damage is a foundation, drainage, or leak problem. A dehumidifier is the wrong solution. Get it diagnosed first."
        }
      ]
    },
    {
      "slotId": "opening_tote",
      "slotLabel": "Labeled \"Spring Opening\" supply tote",
      "slotKind": "core",
      "conditionalOn": [
        "has_organized_supplies"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "opening_tote"
          ],
          "mustHaveRoles": [
            "organizer"
          ],
          "excludeAlreadyHaveFlag": "has_organized_supplies",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Sterilite latching totes seal against critters and moisture. Labeled clearly so anyone (you, partner, property manager) finds it instantly.",
      "contextNote": "Refill in the fall after closing — write a 'replenish list' in the tote so the next opening doesn't surprise you.",
      "citations": [
        "Sterilite product line documentation"
      ],
      "slotPurpose": "Centralize spring opening supplies so they're at the property, ready to use, without a Lowe's run on day one.",
      "whyItMatters": "Driving to Lowe's during opening weekend costs 2-3 hours of weekend time. A pre-stocked tote at the property eliminates that trip.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "basic_consumables",
        "reason": "You're organized. The next-step gap is making sure consumables (batteries, bulbs, filters) are stocked, not just the tote being labeled."
      }
    },
    {
      "slotId": "opening_consumables",
      "slotLabel": "Basic consumables (batteries, bulbs, lighter)",
      "slotKind": "core",
      "conditionalOn": [
        "has_consumables_stocked"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "basic_consumables"
          ],
          "mustHaveRoles": [
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_consumables_stocked",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Mixed pack covers the most common battery sizes; LED bulbs are universal (60W eq is the standard residential). Lighter for grill, fireplace, candle. Duct tape for the inevitable problem.",
      "whyNotCheaper": "There's no real cheaper version. Battery and bulb costs are what they are.",
      "whyNotPremium": "Premium consumable kits add specialty bulbs and exotic batteries you don't need.",
      "citations": [
        "Smoke detector battery replacement standards"
      ],
      "slotPurpose": "Have replacements on-hand for the supplies that always run out at the worst time.",
      "whyItMatters": "A dead smoke detector battery on opening night is annoying. A dead smoke detector battery during a 2am alarm is a real problem. Stock replacements before you need them."
    },
    {
      "slotId": "opening_shutoff_labels",
      "slotLabel": "Shutoff valve labels (if not already done)",
      "slotKind": "addon",
      "conditionalOn": [
        "has_shutoff_labels"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "shutoff_labels"
          ],
          "mustHaveRoles": [
            "document_aid",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_shutoff_labels",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "If you already labeled in fall, this slot is skipped via state-probe. If you didn't, do it now.",
      "contextNote": "This slot reuses the universe entry from outdoor_freeze_prevention via tag merge — same product, same Amazon listing, no duplication.",
      "citations": [
        "Cross-scope universe reuse pattern (v7.2.4 architecture)"
      ],
      "slotPurpose": "Spring is a good time to refresh labels that may have peeled or faded over winter.",
      "whyItMatters": "Same as freeze prevention — anyone in the house should be able to find shutoffs in an emergency."
    }
  ],
  "skipList": [
    {
      "id": "skip_filter_no_housing_check",
      "type": "wrong_version",
      "title": "Buying water filters before checking housing size",
      "marketingPitch": "Universal-fit replacement filter, works with all systems.",
      "realReason": "Filters come in incompatible sizes — 10\", 4.5\"x10\", 4.5\"x20\", proprietary models. \"Universal\" is a marketing claim. The wrong size doesn't seal, water bypasses the filter, and you've wasted $30. Photograph and measure the housing first.",
      "amountSaved": {
        "low": 25,
        "high": 45
      },
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Pentek and generic filter sizing guidance"
      ]
    },
    {
      "id": "skip_fridge_filter_for_sediment",
      "type": "wrong_version",
      "title": "Fridge filters when the issue is whole-house sediment",
      "marketingPitch": "Convenient inline filter, replaces every 6 months.",
      "realReason": "Fridge filters handle taste/smell at one fixture. They don't address whole-house sediment that's also affecting your shower and washing machine. If the issue is taste at the kitchen tap, the fridge filter is right. If it's sediment everywhere, you need whole-house filtration.",
      "amountSaved": {
        "low": 35,
        "high": 60
      },
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Whole-house vs point-of-use filter selection guide"
      ]
    },
    {
      "id": "skip_dehumidifier_water_source_unknown",
      "type": "wrong_version",
      "title": "Dehumidifier when the real issue is drainage or leaks",
      "marketingPitch": "Whole-basement humidity control.",
      "realReason": "Dehumidifiers treat ambient moisture. They don't fix water sources. If your basement floods because of foundation drainage, the dehumidifier runs continuously, costs $50/month in electricity, and the floor still gets wet. Diagnose source first.",
      "amountSaved": {
        "low": 200,
        "high": 320
      },
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "EPA basement moisture diagnosis guidance"
      ]
    },
    {
      "id": "skip_full_kit_when_only_consumables",
      "type": "wrong_version",
      "title": "Full cleaning kits when only consumables needed",
      "marketingPitch": "Complete spring cleaning starter set.",
      "realReason": "If your second home already has buckets, mops, gloves, and basic supplies stored, the kit duplicates what you have. Buy consumables only — bleach, microfiber, multi-surface cleaner — and you've saved $30 plus you don't accumulate redundant gear.",
      "amountSaved": {
        "low": 25,
        "high": 45
      },
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Cleaning supply per-item vs kit pricing"
      ]
    },
    {
      "id": "skip_cheap_moisture_meter",
      "type": "wrong_version",
      "title": "Cheap moisture meters with poor usefulness",
      "marketingPitch": "\"Detects all moisture problems.\"",
      "realReason": "$10-20 meters at the bottom of the price range have inconsistent readings and limited probe depth. They produce numbers that look authoritative but mislead diagnosis. If you need a moisture meter, the $40-60 General Tools or Klein meter is the right tier; below that is hobbyist quality with professional-looking output.",
      "amountSaved": {
        "low": 10,
        "high": 25
      },
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Moisture meter accuracy testing"
      ]
    },
    {
      "id": "skip_outdoor_furniture_at_opening",
      "type": "wrong_category",
      "title": "Buying outdoor furniture during opening week",
      "realReason": "Smart Cart's outdoor_lake_season covers furniture decisions properly. Spring opening should focus on water, leaks, cleaning, and filters — not new chairs. Furniture shopping during opening eats your weekend and gets you the wrong chairs (no time to compare). Defer to a separate decision.",
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Sequential project planning principles"
      ]
    },
    {
      "id": "skip_smart_lock_during_opening",
      "type": "wrong_category",
      "title": "Smart lock installation during spring opening",
      "realReason": "Smart locks are great. Installation during your already-busy opening weekend is the wrong timing. Schedule it for a quieter weekend in May or June — the wrong-time lock costs more in frustration than it saves in convenience.",
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Property setup project sequencing"
      ]
    },
    {
      "id": "skip_lawn_mower_purchase_opening",
      "type": "wrong_category",
      "title": "Major lawn equipment purchases during opening week",
      "realReason": "Same logic — mower, leaf blower, chainsaw decisions deserve their own research. During opening week you're triaging actual problems. Defer the large purchase decision to once the property is open and you can actually test what you need.",
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "Project sequencing and decision quality"
      ]
    },
    {
      "id": "skip_rebadged_municipal_test",
      "type": "wrong_category",
      "title": "Buying lab tests for municipal water",
      "realReason": "Municipal water systems test their water continuously and publish results. Vermont's reports are publicly available. A homeowner lab test on municipal water is duplicating work the utility already does. Save the money and read the utility's annual report.",
      "appliesToScope": [
        "outdoor_seasonal_opening"
      ],
      "citations": [
        "EPA municipal water testing requirements"
      ]
    }
  ],
  "scenarioDefaults": {
    "just_starting": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    },
    "already_have_basics": {
      "selectedTier": "sweet_spot",
      "alreadyHave": [
        "has_organized_supplies",
        "has_consumables_stocked",
        "has_shutoff_labels"
      ]
    },
    "tight_budget": {
      "selectedTier": "budget",
      "alreadyHave": []
    },
    "absentee_owner": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    }
  },
  "smartCartPromise": "Avoid losing your first weekend to leaks, missing supplies, filter mistakes, and reset work.",
  "primaryCustomerPain": "Opening day at a Vermont second home should be relaxing. It's usually a list of small surprises — a slow leak, a clogged filter, a moldy bathroom — that eat your first weekend.",
  "valueProposition": "A $150 opening kit prepared in advance prevents 4-6 hours of unplanned shopping trips during a 48-hour visit. The math is real: weekend trips to the lake have fixed travel time; every hour spent at Lowe's is an hour off the dock.",
  "routeOutRules": [
    {
      "condition": "has_visible_water_damage",
      "destination": "small_pro",
      "reason": "Water damage discovered at opening is a plumber problem, not a Smart Cart problem. Get it assessed before doing anything else."
    },
    {
      "condition": "has_septic_concerns",
      "destination": "small_pro",
      "reason": "Septic system concerns at opening (slow drains, odor, ground saturation) need a septic pro, not a kit. Especially in Vermont where septic systems often need post-winter inspection."
    }
  ],
  "seasonalUrgency": {
    "season": "spring_opening",
    "deadline": "04-15",
    "label": "Best by mid-April so your kit is at the property before opening weekend, not arriving at the wrong address while you wait."
  }
}
