// V7.2.5 — Trimmed outdoor_dock_lake scope catalog.
//
// Generated by scripts/ingest-catalog.ts from
// scripts/source-catalogs/outdoor-dock-lake.ts.
// Editorial layer only. Product data lives in
// src/content/smart-cart/universe.ts.

import type { ScopeCatalog } from '@/lib/smart-cart-model'

export const OUTDOOR_DOCK_LAKE: ScopeCatalog = {
  "topic": "outdoor",
  "scopeVariantId": "outdoor_dock_lake",
  "scenarios": [
    "lake_property",
    "just_starting",
    "already_have_basics",
    "tight_budget"
  ],
  "slots": [
    {
      "slotId": "dock_lines",
      "slotLabel": "Dock lines / mooring rope",
      "slotKind": "core",
      "conditionalOn": [
        "has_dock_lines"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_lines"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_lines",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_lines"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_lines",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_lines"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_lines",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "New England Ropes 5/8\" 4-pack covers the typical 25-30 ft boat with bow, stern, and two spring lines. Marine-grade nylon resists UV and mildew. Lasts 5-7 seasons in Vermont conditions.",
      "whyNotCheaper": "Generic nylon stiffens within 1-2 seasons. The eye splices unravel; the rope chafes through at the cleat. The $15 saved means buying again next year.",
      "whyNotPremium": "Yale Cordage is for boats where mooring precision matters (racing, expensive yachts). For a typical Vermont lake property dock, the New England Ropes line is the right tier.",
      "contextNote": "Always have at least 4 lines per boat: bow, stern, and two spring lines (forward and aft). Lines should be 1.5-2x the boat length for good shock absorption.",
      "citations": [
        "New England Ropes product documentation",
        "Marine line sizing standards"
      ],
      "slotPurpose": "Tie the boat to the dock without it drifting, banging the dock, or breaking free in storms.",
      "whyItMatters": "Cheap rope stiffens, frays, and breaks. A broken dock line during a storm is how boats end up against rocks or floating loose at 3am.",
      "commonMistake": "Sizing rope to boat weight rather than to dock cleat hardware. 1/2\" rope works for boats under 25 ft; 5/8\" is the standard for 25-35 ft. Cheap rope of any size eventually fails.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "dock_bumpers",
        "reason": "You have lines. The next-step gap is bumpers between boat and dock — without them, the lines do all the work and the hull and dock both wear."
      }
    },
    {
      "slotId": "dock_bumpers",
      "slotLabel": "Dock bumpers / fenders",
      "slotKind": "core",
      "conditionalOn": [
        "has_dock_bumpers"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_bumpers"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_bumpers",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_bumpers"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_bumpers",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_bumpers"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_bumpers",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Taylor Made is the marine standard for the price. Closed-cell vinyl resists puncture, UV, and weather. 8-10 year life in typical Vermont conditions.",
      "whyNotCheaper": "Generic vinyl fenders work for 3-5 years before UV degradation makes them brittle and they crack under impact. The Taylor Made earns its premium in lifespan alone.",
      "whyNotPremium": "Polyform G-series is pro-grade for boats over 30 ft or harsh marine environments (saltwater, ocean spray). For Vermont freshwater, Taylor Made is right-sized.",
      "contextNote": "Mount bumpers on the boat (move with the boat) for daily mooring. Mount on the dock for visiting boats or where the dock contacts at fixed points.",
      "citations": [
        "Taylor Made marine product documentation",
        "Boat fender material durability"
      ],
      "slotPurpose": "Cushion the boat-dock interface so neither one wears or damages.",
      "whyItMatters": "Without bumpers, hull and dock contact each other directly. Wave action becomes daily impact. Hull paint chips, dock boards crack at contact points, fasteners loosen. Bumpers absorb the impact."
    },
    {
      "slotId": "dock_marine_hardware",
      "slotLabel": "Marine-grade stainless hardware (replacement set)",
      "slotKind": "core",
      "conditionalOn": [
        "has_marine_hardware"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "marine_hardware"
          ],
          "mustHaveRoles": [
            "hardware"
          ],
          "excludeAlreadyHaveFlag": "has_marine_hardware",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "316 stainless assortment kit covers the common sizes. ~$45 once, lasts the lifetime of the dock.",
      "whyNotCheaper": "Galvanized hardware is half the price; lifespan is 1-3 seasons vs 30+ for 316 stainless. The math favors stainless once you account for replacement cycles.",
      "whyNotPremium": "There's no real premium tier. 316 stainless is the right material; brand variation is small.",
      "contextNote": "Inspect dock hardware annually. Pulled-out lag bolts at cleats are the #1 dock failure point. Replace any showing rust streaks.",
      "citations": [
        "316 stainless steel marine corrosion testing",
        "Dock hardware standards"
      ],
      "slotPurpose": "Replace rusted, corroded, or undersized fasteners on dock cleats, eye bolts, and structural connections.",
      "whyItMatters": "Galvanized hardware rusts within 1-3 seasons in lake water. Zinc-plated hardware rusts faster. 304 stainless rusts in saltwater (Vermont freshwater is fine for 304); 316 stainless is the universal marine standard. Wrong fasteners on dock hardware = injuries when they fail.",
      "commonMistake": "Using zinc-plated or galvanized hardware on dock connections. Looks fine for 6 months, fails by year 2. The wet/dry cycle accelerates corrosion. Always 316 stainless on anything submerged or splashed.",
      "nextBestIfAlreadyHave": {
        "targetSlotOrFunction": "dock_lighting",
        "reason": "Hardware is current. The next-step gap is dock lighting for evening safety — most dock injuries happen in low light."
      }
    },
    {
      "slotId": "dock_lighting",
      "slotLabel": "Dock edge lighting",
      "slotKind": "core",
      "conditionalOn": [
        "has_dock_lighting"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_lighting"
          ],
          "mustHaveRoles": [
            "lighting"
          ],
          "excludeAlreadyHaveFlag": "has_dock_lighting",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_lighting"
          ],
          "mustHaveRoles": [
            "lighting"
          ],
          "excludeAlreadyHaveFlag": "has_dock_lighting",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_lighting"
          ],
          "mustHaveRoles": [
            "lighting"
          ],
          "excludeAlreadyHaveFlag": "has_dock_lighting",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "Dock Edge low-voltage rope kit is the marine-standard residential dock lighting. 50 ft of continuous edge lighting, weatherproof connectors, dusk-to-dawn timing. Reliable for 5-7 years.",
      "whyNotCheaper": "Solar lights look great in marketing photos and fail consistently in real cold-climate lake conditions. The $25-50 saved buys a 1-year solution at most.",
      "whyNotPremium": "Hardwired marine lights are for commercial docks or where motion sensing is required. For residential dock safety lighting, the rope kit covers all needs.",
      "contextNote": "Run the rope along the outboard edge of the dock so light shines toward the water — illuminates the edge for walkers AND approaching boats. Cover the wire with rubber edge guard so it doesn't get caught on shoes.",
      "citations": [
        "Dock Edge product documentation",
        "Marine LED lighting durability"
      ],
      "slotPurpose": "Light the dock edge after dark for safe walking and boat approach.",
      "whyItMatters": "Slips and falls on docks happen mostly in low light. Dock edge lighting is the highest-leverage safety upgrade after the bumpers and lines are sound.",
      "commonMistake": "Buying solar lights that fail in 1-2 seasons. The Vermont winter freezes the batteries; UV degrades the housings. Solar is fine for visual marking; for actual reliable light, hardwired or low-voltage transformer is the right call."
    },
    {
      "slotId": "dock_ladder",
      "slotLabel": "Dock ladder (swim ladder)",
      "slotKind": "core",
      "conditionalOn": [
        "has_dock_ladder"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_ladder"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_ladder",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_ladder"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_ladder",
          "tier": "sweet_spot",
          "limit": 1
        },
        "premium": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "dock_ladder"
          ],
          "mustHaveRoles": [
            "hardware",
            "safety_item"
          ],
          "excludeAlreadyHaveFlag": "has_dock_ladder",
          "tier": "premium",
          "limit": 1
        }
      },
      "whyThis": "JIF Marine 5-step is the verified marine pick. Polyethylene steps are warmer than aluminum (matters when the ladder is in the sun), 350 lb capacity handles all guests, lifetime frame warranty. Rust-resistant aluminum handles freshwater fine.",
      "whyNotCheaper": "Generic 4-step ladders work for small kids and lightweight adults. Once you have heavier guests or arthritis-affected joints, the cheaper ladder feels unsafe.",
      "whyNotPremium": "Custom stainless ladders are 30-year products and aesthetic statements. JIF Marine delivers the same safety profile.",
      "contextNote": "Match the step count to your typical water depth. 4-step is fine for shallow shorelines; 5-step is right for typical lakeshore. 6-step exists for deep-water docks.",
      "citations": [
        "JIF Marine product documentation",
        "Dock ladder safety standards"
      ],
      "slotPurpose": "Safe entry/exit from the water at the dock.",
      "whyItMatters": "A wobbly or rusted ladder is a primary injury vector. Older adults, kids, and tipsy adults all rely on the ladder to get out of the water — making it sturdy is a safety basic, not a luxury.",
      "commonMistake": "Telescoping ladders that flex under load. They feel sturdy at the top but bow at the middle, throwing balance. The welded-frame ladder doesn't flex."
    },
    {
      "slotId": "dock_mildew_cleaner",
      "slotLabel": "Mildew cleaner (decking + furniture)",
      "slotKind": "core",
      "conditionalOn": [
        "has_mildew_cleaner"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "mildew_cleaner"
          ],
          "mustHaveRoles": [
            "cleaner",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_mildew_cleaner",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Wet & Forget is the verified no-effort solution. Apply with a pump sprayer once a year (early summer), walk away. It works over weeks, killing mildew at the spore level. No scrubbing, no pressure washing required.",
      "whyNotCheaper": "Bleach works but damages wood and kills nearby plants in runoff. Wet & Forget targets only the mildew without collateral damage.",
      "whyNotPremium": "Premium 'marine-only' cleaners exist for $50+; they do the same job as Wet & Forget at twice the price.",
      "contextNote": "Apply on a dry, mild-temperature day with no rain forecast for 6 hours. The product needs time to penetrate before being washed off.",
      "citations": [
        "Wet & Forget product documentation",
        "Dock surface mildew prevention guidance"
      ],
      "slotPurpose": "Remove green mildew and algae buildup on dock boards and outdoor surfaces without aggressive scrubbing.",
      "whyItMatters": "Mildew on dock boards is slippery — the algae that looks green and harmless is the cause of most dock slips. Annual cleaning prevents the surface from getting glossy-slippery."
    },
    {
      "slotId": "dock_storage_bin",
      "slotLabel": "Weatherproof dock storage bin",
      "slotKind": "addon",
      "conditionalOn": [
        "has_dock_storage"
      ],
      "tierQueries": {
        "budget": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "weatherproof_bin"
          ],
          "mustHaveRoles": [
            "organizer"
          ],
          "excludeAlreadyHaveFlag": "has_dock_storage",
          "tier": "budget",
          "limit": 1
        },
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "weatherproof_bin"
          ],
          "mustHaveRoles": [
            "organizer"
          ],
          "excludeAlreadyHaveFlag": "has_dock_storage",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Suncast 73-gallon doubles as a bench, which is genuinely useful at a dock. Holds the standard load of lake gear without being so big that things get lost in it.",
      "whyNotCheaper": "50-gallon is fine for minimal needs (4 life jackets, basic tools). Most lake families need more capacity.",
      "whyNotPremium": "Premium teak or cedar dock boxes are aesthetic statements at $400-800. Same storage function.",
      "citations": [
        "Suncast product line documentation"
      ],
      "slotPurpose": "Centralize lake essentials at the dock so they're at hand and not running back and forth to the house.",
      "whyItMatters": "Without dockside storage, every visit involves trips back to the house for forgotten items. The bin removes that friction and keeps things dry.",
      "commonMistake": "Oversized dock boxes that trap moisture. A 100+ gallon box with poor ventilation grows mildew on everything stored inside. Right-sized with breathing slots is the correct approach."
    },
    {
      "slotId": "dock_non_slip_strips",
      "slotLabel": "Anti-slip strips for dock surface",
      "slotKind": "addon",
      "conditionalOn": [
        "has_non_slip_strips"
      ],
      "tierQueries": {
        "sweet_spot": {
          "mustHaveTopics": [
            "outdoor"
          ],
          "mustHaveFunctions": [
            "non_slip_strips"
          ],
          "mustHaveRoles": [
            "safety_item",
            "consumable_material"
          ],
          "excludeAlreadyHaveFlag": "has_non_slip_strips",
          "tier": "sweet_spot",
          "limit": 1
        }
      },
      "whyThis": "Marine-grade variant of the deck refresh tape. Cross-scope reuse — same product, reapplied for dock-specific use.",
      "citations": [
        "Cross-scope universe reuse pattern"
      ],
      "slotPurpose": "Prevent slips on wet dock boards, especially the stairs from dock to lake or shore.",
      "whyItMatters": "Wet dock boards combined with mildew are the most slippery surface on the property. Anti-slip strips at high-traffic spots (dock entry, stairs, ladder approach) reduce slip injuries."
    }
  ],
  "skipList": [
    {
      "id": "skip_zinc_hardware_marine",
      "type": "wrong_version",
      "title": "Zinc-plated or galvanized hardware on dock connections",
      "marketingPitch": "Standard hardware, half the price.",
      "realReason": "Looks fine for 6 months. Rusts within 1-3 seasons in lake water. The wet/dry cycle accelerates corrosion. Cleat or eye-bolt failure under load is how dock injuries happen. Always 316 stainless on anything submerged or splashed.",
      "amountSaved": {
        "low": 25,
        "high": 50
      },
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Marine fastener corrosion testing"
      ]
    },
    {
      "id": "skip_solar_dock_lights",
      "type": "wrong_version",
      "title": "Solar dock lights as primary lighting",
      "marketingPitch": "No wiring, no electricity bill.",
      "realReason": "Solar dock lights fail in 1-2 seasons. Vermont winter freezes the batteries; UV degrades the housings. They look great in spring marketing photos and rarely make it to year 3. Low-voltage rope lighting with a transformer is the right tier for residential dock lighting.",
      "amountSaved": {
        "low": 60,
        "high": 120
      },
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Solar light cold-climate failure data"
      ]
    },
    {
      "id": "skip_oversized_dock_box",
      "type": "wrong_version",
      "title": "Oversized dock storage boxes (100+ gallons)",
      "marketingPitch": "Maximum storage capacity.",
      "realReason": "Large bins with poor ventilation trap moisture. Within one season, contents grow mildew and the bin smells. Right-size to actual storage need (50-75 gallons typical) plus breathing slots. The 100+ gallon bin is the wrong shape for the wet-gear use case.",
      "amountSaved": {
        "low": 80,
        "high": 200
      },
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Dock storage moisture management"
      ]
    },
    {
      "id": "skip_cheap_rope_dock",
      "type": "wrong_version",
      "title": "Cheap braided polypropylene rope as dock lines",
      "marketingPitch": "Lightweight, inexpensive marine rope.",
      "realReason": "Polypropylene floats (good) but stiffens, fades, and frays within 1-2 seasons. Polypropylene also has lower break strength than nylon. For dock lines, marine-grade nylon double-braid is the right material; polypropylene is for ski tow ropes and casual use.",
      "amountSaved": {
        "low": 25,
        "high": 60
      },
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Marine rope fiber comparison"
      ]
    },
    {
      "id": "skip_premium_marine_no_problem",
      "type": "wrong_category",
      "title": "Premium marine gear before any specific problem exists",
      "realReason": "Yale Cordage rope, Polyform fenders, custom stainless ladders are upgrades you make when something specific isn't working. Buying them all preemptively at $1,500+ is over-engineering. Start with the sweet-spot tier and upgrade specific items as you identify weaknesses.",
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Dock gear upgrade sequencing"
      ]
    },
    {
      "id": "skip_dock_movement_hardware",
      "type": "wrong_category",
      "title": "Hardware upgrades on a dock with structural movement",
      "realReason": "If your dock rocks, sways, or has settled posts, hardware upgrades don't fix it. The dock has structural problems. New cleats on a wobbly dock just creates a stronger handle for wave loads — and the underlying structure still fails. Get a marine pro or experienced contractor.",
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Dock structural assessment guidance"
      ]
    },
    {
      "id": "skip_decorative_lake_hardware",
      "type": "wrong_category",
      "title": "Decorative cast-iron / nautical-themed dock hardware",
      "realReason": "Cast iron rusts in lake conditions even with paint. The 'old maritime' look at $200+ for cleats and rings is a 2-year aesthetic. 316 stainless or marine bronze are the materials that actually survive — and they look fine.",
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Dock hardware material durability"
      ]
    },
    {
      "id": "skip_dock_box_subscription",
      "type": "wrong_category",
      "title": "Subscription dock-supply services",
      "realReason": "Recurring delivery of dock essentials at $20-50/month. The supplies last 3-5 years; you don't need monthly delivery. Marketing construct.",
      "appliesToScope": [
        "outdoor_dock_lake"
      ],
      "citations": [
        "Subscription service applicability"
      ]
    }
  ],
  "scenarioDefaults": {
    "lake_property": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    },
    "just_starting": {
      "selectedTier": "sweet_spot",
      "alreadyHave": []
    },
    "already_have_basics": {
      "selectedTier": "sweet_spot",
      "alreadyHave": [
        "has_dock_lines",
        "has_dock_bumpers"
      ]
    },
    "tight_budget": {
      "selectedTier": "budget",
      "alreadyHave": []
    }
  },
  "smartCartPromise": "Make the dock and lake setup safer and more usable without turning every issue into a rebuild.",
  "primaryCustomerPain": "Lake-property dock issues escalate fast: rotted boards become pulled fasteners; pulled fasteners become loose rails; loose rails become injuries. Catching issues at the small-fix stage saves 10x the cost of a rebuild.",
  "valueProposition": "$300-$800 of right-sized dock hardware and safety upgrades preserves the dock for 5-10 more years and eliminates the most common injury risks.",
  "routeOutRules": [
    {
      "condition": "has_structural_dock_movement",
      "destination": "small_pro",
      "reason": "Dock that shifts, rocks, or has settled posts is a structural problem. Hardware upgrades don't fix foundation issues. Get a marine pro or experienced contractor."
    },
    {
      "condition": "planning_full_dock_replacement",
      "destination": "contractor",
      "reason": "Full dock replacement at $5,000-$25,000+ is a contractor project. Smart Cart covers the maintenance window before replacement; replacement itself is contractor scope."
    }
  ],
  "seasonalUrgency": {
    "season": "spring_opening",
    "deadline": "05-15",
    "label": "Best by mid-May. Vermont lake properties open Memorial Day; dock hardware should be installed before guests arrive."
  }
}
