'use client'
import { useState, useRef, useEffect } from 'react'
interface Strength{point:string;detail:string}
interface Concern{title:string;whyCheck:string;howToResolve:string;resolvedWhen:string;cost:string}
interface ActionItem{title:string;priority:string;why:string;whatItUnlocks:string;nextStep:string;timing:string}
interface Avoidance{action:string;why:string}
interface SeasonalItem{action:string;why:string;timing:string}
interface ProgramScreen{name:string;why:string;value:string;caveat:string;url?:string}
interface ProjectIdea{title:string;scope:'big'|'small';cost:string;impact:string;dependencies:string;timing:string}
interface DataLink{label:string;url:string;what:string}
interface SnapshotFact{label:string;value:string}
interface GISData{geocoded:boolean;lat?:number;lng?:number;matchScore?:number;matchType?:string;floodZone?:string;inFloodZone?:boolean;inShoreland?:boolean;inRiverCorridor?:boolean;inWetland?:boolean}
interface Report{summary:string;snapshot:{address:string;town:string;county:string;facts:SnapshotFact[]};strengths:Strength[];concerns:Concern[];actions:ActionItem[];projects:ProjectIdea[];avoidances:Avoidance[];seasonal:SeasonalItem[];reasoning:string;programs:ProgramScreen[];dataLinks:DataLink[];gis?:GISData;generatedAt:string}
const VT_TOWNS=['Addison','Albany','Alburgh','Arlington','Athens','Averill','Bakersfield','Barnard','Barnet','Barre','Barton','Belvidere','Bennington','Berkshire','Berlin','Bethel','Bolton','Bradford','Braintree','Brandon','Brattleboro','Bridgewater','Bridport','Brighton','Bristol','Brookfield','Brookline','Brownington','Brunswick','Burke','Burlington','Cabot','Calais','Cambridge','Canaan','Castleton','Cavendish','Charleston','Charlotte','Chelsea','Chester','Chittenden','Clarendon','Colchester','Concord','Corinth','Cornwall','Coventry','Craftsbury','Danby','Danville','Derby','Dorset','Dover','Dummerston','Duxbury','East Haven','East Montpelier','Eden','Elmore','Enosburg','Enosburg Falls','Essex','Essex Junction','Fairfax','Fairfield','Fairlee','Fayston','Ferrisburgh','Fletcher','Franklin','Georgia','Glastenbury','Glover','Goshen','Grafton','Granby','Grand Isle','Granville','Greensboro','Groton','Guildhall','Guilford','Halifax','Hancock','Hardwick','Hartford','Hartland','Highgate','Hinesburg','Holland','Huntington','Hyde Park','Ira','Irasburg','Isle La Motte','Jamaica','Jay','Jericho','Johnson','Killington','Kirby','Landgrove','Leicester','Lemington','Lincoln','Londonderry','Lowell','Ludlow','Lunenburg','Lyndon','Lyndonville','Maidstone','Manchester','Marlboro','Marshfield','Mendon','Middlesex','Middlebury','Middletown Springs','Milton','Monkton','Montgomery','Montpelier','Moretown','Morgan','Morristown','Morrisville','Mount Holly','Mount Tabor','New Haven','Newbury','Newfane','Newport','North Hero','Northfield','Norton','Norwich','Orange','Orwell','Panton','Pawlet','Peacham','Peru','Pittsfield','Pittsford','Plainfield','Plymouth','Pomfret','Poultney','Pownal','Proctor','Putney','Quechee','Randolph','Reading','Readsboro','Richmond','Richford','Ripton','Rochester','Rockingham','Roxbury','Royalton','Rupert','Rutland','Ryegate','Salisbury','Sandgate','Saxtons River','Searsburg','Shaftsbury','Sharon','Sheffield','Shelburne','Sheldon','Sherburne','Shoreham','Shrewsbury','Somerset','South Burlington','South Hero','Springfield','St. Albans','St. George','St. Johnsbury','Stamford','Stannard','Starksboro','Stockbridge','Stowe','Strafford','Stratton','Sudbury','Sunderland','Sutton','Swanton','Thetford','Tinmouth','Topsham','Townshend','Troy','Tunbridge','Underhill','Vergennes','Vernon','Vershire','Victory','Waitsfield','Walden','Wallingford','Waltham','Wardsboro','Warren','Washington','Waterbury','Waterford','Waterville','Weathersfield','Wells','West Dover','West Fairlee','West Rutland','West Windsor','Westfield','Westford','Westminster','Westmore','Weston','Weybridge','Wheelock','White River Junction','Whitingham','Whiting','Williston','Wilmington','Windham','Windsor','Winhall','Winooski','Wolcott','Woodbury','Woodford','Woodstock','Worcester']
const EX=['142 Lakeshore Drive, Greensboro, VT','78 Mountain View Road, Stowe, VT','455 East Hill Road, Peacham, VT','22 Sunset Point, Charlotte, VT','9 Birch Lane, Wilmington, VT']
export default function Page(){
  const[addr,setAddr]=useState('');const[r,setR]=useState<Report|null>(null);const[loading,setLoading]=useState(false);const[err,setErr]=useState('');const[sug,setSug]=useState('');const[dd,setDd]=useState(false);const[fl,setFl]=useState<string[]>([]);const iR=useRef<HTMLInputElement>(null);const dR=useRef<HTMLDivElement>(null)
  useEffect(()=>{const h=(e:MouseEvent)=>{if(dR.current&&!dR.current.contains(e.target as Node)&&iR.current&&!iR.current.contains(e.target as Node))setDd(false)};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[])
  function onType(v:string){setAddr(v);const parts=v.split(',');const last=(parts.length>1?parts[parts.length-1]:'').trim().replace(/\s*(VT|Vermont)\s*/gi,'').trim();const s=last||(parts.length===1&&v.length>3?v.split(' ').slice(-1)[0]:'');if(s&&s.length>=2){const l=s.toLowerCase();const m=[...VT_TOWNS.filter(t=>t.toLowerCase().startsWith(l)),...VT_TOWNS.filter(t=>!t.toLowerCase().startsWith(l)&&t.toLowerCase().includes(l))].slice(0,6);setFl(m);setDd(m.length>0)}else{setDd(false);setFl([])}}
  function pick(t:string){const p=addr.split(',');if(p.length>=2){p[p.length-1]=' '+t+', VT';setAddr(p.slice(0,-1).join(',')+','+p[p.length-1])}else setAddr(addr.trim()+(addr.trim()?', ':'')+t+', VT');setDd(false);iR.current?.focus()}
  async function go(a?:string){const t=a||addr;if(!t.trim())return;setAddr(t);setLoading(true);setErr('');setSug('');setR(null);setDd(false);try{const res=await fetch('/api/seasonal-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address:t})});const d=await res.json();if(!res.ok){setErr(d.error||'Failed.');setSug(d.suggestion||'')}else setR(d)}catch{setErr('Network error.')}finally{setLoading(false)}}
  return(<div className="min-h-screen bg-white" style={{fontFamily:'"DM Sans",system-ui,sans-serif'}}><nav className="border-b border-stone-100 px-6 py-5"><div className="max-w-2xl mx-auto"><a href="/" className="text-base font-semibold text-stone-900 tracking-tight" style={{fontFamily:'"Playfair Display",Georgia,serif'}}>Alder Projects</a></div></nav><main className="max-w-2xl mx-auto px-6 pt-12 pb-16"><div className="mb-12"><h1 className="text-3xl font-semibold text-stone-900 tracking-tight mb-3" style={{fontFamily:'"Playfair Display",Georgia,serif'}}>Seasonal Home<br/>Analysis</h1><p className="text-stone-400 text-sm mb-8">Enter any Vermont address</p>
    <form onSubmit={e=>{e.preventDefault();go()}} className="flex gap-2 mb-4"><div className="flex-1 relative"><input ref={iR} type="text" value={addr} onChange={e=>onType(e.target.value)} onFocus={()=>{if(fl.length>0)setDd(true)}} placeholder="Street, Town, VT" className="w-full px-4 py-3 bg-stone-50 border border-stone-200 rounded-xl text-sm text-stone-900 placeholder:text-stone-300 focus:outline-none focus:ring-2 focus:ring-stone-300 focus:bg-white transition-all" autoComplete="off"/>{dd&&fl.length>0&&(<div ref={dR} className="absolute z-10 left-0 right-0 top-full mt-1 bg-white border border-stone-200 rounded-xl shadow-xl overflow-hidden">{fl.map(t=>(<button key={t} type="button" onClick={()=>pick(t)} className="w-full text-left px-4 py-2.5 text-sm text-stone-600 hover:bg-stone-50 hover:text-stone-900 transition-colors">{t}<span className="text-stone-300 ml-1">, VT</span></button>))}</div>)}</div><button type="submit" disabled={loading||!addr.trim()} className="px-5 py-3 bg-stone-900 text-white text-sm font-medium rounded-xl hover:bg-stone-800 disabled:opacity-40 transition-all">{loading?'...':'Analyze'}</button></form>
    {!r&&!loading&&(<div className="flex flex-wrap gap-1.5">{EX.map(ex=>(<button key={ex} onClick={()=>go(ex)} className="text-xs px-3 py-1 rounded-full bg-stone-50 text-stone-400 hover:bg-stone-100 hover:text-stone-600 transition-all">{ex.split(',')[1]?.trim()}</button>))}</div>)}
    {err&&(<div className="mt-4 p-3 bg-red-50 rounded-xl text-sm text-red-700">{err}{sug&&<span className="text-red-500 ml-1">{sug}</span>}</div>)}</div>
    {loading&&(<div className="text-center py-20"><div className="inline-block w-5 h-5 border-2 border-stone-200 border-t-stone-600 rounded-full animate-spin"/></div>)}
    {r&&(<div className="space-y-10">
      <div><p className="text-xs text-stone-300 uppercase tracking-widest mb-3">{r.snapshot.address}</p><p className="text-stone-700 text-base leading-relaxed">{r.summary}</p><div className="flex flex-wrap gap-x-5 gap-y-1 mt-4 text-xs text-stone-400">{r.snapshot.facts.map(f=>(<span key={f.label}><span className="text-stone-300">{f.label}</span> {f.value}</span>))}</div>{r.gis?.geocoded&&(<div className="mt-3 flex items-center gap-1.5 text-[10px] text-emerald-600"><span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-500"></span>Live GIS data — FEMA flood maps, ANR shoreland &amp; wetland layers, VT E911 geocoder</div>)}{r.gis&&!r.gis.geocoded&&(<div className="mt-3 flex items-center gap-1.5 text-[10px] text-stone-400"><span className="inline-block w-1.5 h-1.5 rounded-full bg-stone-300"></span>Address could not be geocoded — findings based on town-level data only.</div>)}</div>
      <div><H>What this property has going for it</H><div className="grid grid-cols-2 gap-2 mt-3">{r.strengths.map(s=>(<div key={s.point} className="bg-emerald-50 rounded-xl p-3"><p className="text-xs font-semibold text-emerald-800">{s.point}</p><p className="text-xs text-emerald-700 mt-0.5 leading-relaxed">{s.detail.split('.')[0]}.</p></div>))}</div></div>
      <div><H>What to check</H><div className="space-y-2 mt-3">{r.concerns.map(c=>(<details key={c.title} className="group bg-stone-50 rounded-xl overflow-hidden"><summary className="flex items-center justify-between px-4 py-3 cursor-pointer text-sm font-medium text-stone-800 hover:bg-stone-100 transition-colors list-none"><span>{c.title}</span><span className="text-xs text-stone-400 group-open:hidden">{c.cost}</span></summary><div className="px-4 pb-4 text-xs space-y-2"><p className="text-stone-500 leading-relaxed">{c.whyCheck}</p><div className="bg-white rounded-lg p-3 border border-stone-100"><p className="text-stone-400 uppercase tracking-wider text-[10px] mb-1">How to resolve</p><p className="text-stone-700">{c.howToResolve}</p></div><div className="flex justify-between text-stone-400"><span className="text-emerald-600">{c.resolvedWhen}</span><span>{c.cost}</span></div></div></details>))}</div></div>
      <div><H>What to do first</H><div className="space-y-1.5 mt-3">{r.actions.map((a,i)=>(<div key={a.title} className="flex gap-3 bg-stone-50 rounded-xl px-4 py-3 items-start"><span className="text-lg font-semibold text-stone-200 leading-none mt-0.5">{i+1}</span><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><p className="text-sm font-medium text-stone-800">{a.title}</p><span className={`text-[10px] font-medium px-1.5 py-0.5 rounded-md ${a.priority==='First'?'bg-stone-900 text-white':'bg-stone-200 text-stone-500'}`}>{a.priority}</span></div><p className="text-xs text-stone-400 mt-0.5">{a.why}</p><p className="text-xs text-emerald-600 mt-1">&rarr; {a.nextStep}</p></div></div>))}</div></div>
      <div><H>Project ideas</H><div className="mt-3 space-y-4"><div><p className="text-[10px] text-stone-400 uppercase tracking-widest mb-2">Quick wins</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{r.projects.filter(p=>p.scope==='small').map(p=>(<div key={p.title} className="bg-sky-50 rounded-xl p-3"><p className="text-xs font-semibold text-sky-900">{p.title}</p><p className="text-xs text-sky-700 mt-0.5">{p.impact.split('.')[0]}.</p><div className="flex justify-between mt-2 text-[10px] text-sky-500"><span>{p.cost}</span><span>{p.timing}</span></div></div>))}</div></div><div><p className="text-[10px] text-stone-400 uppercase tracking-widest mb-2">Major upgrades</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{r.projects.filter(p=>p.scope==='big').map(p=>(<div key={p.title} className="bg-stone-50 rounded-xl p-3 border border-stone-100"><p className="text-xs font-semibold text-stone-800">{p.title}</p><p className="text-xs text-stone-500 mt-0.5">{p.impact.split('.')[0]}.</p><p className="text-[10px] text-stone-400 mt-1">{p.dependencies.split('.')[0]}.</p><div className="flex justify-between mt-2 text-[10px] text-stone-400"><span className="text-emerald-600">{p.cost}</span><span>{p.timing}</span></div></div>))}</div></div></div></div>
      <div><H>Hold off on</H><div className="space-y-1 mt-3">{r.avoidances.map(a=>(<div key={a.action} className="flex items-start gap-2 text-sm px-1 py-1"><span className="text-stone-300 mt-0.5">&times;</span><div><span className="text-stone-700 font-medium">{a.action}</span><span className="text-stone-400 ml-1">&mdash; {a.why}</span></div></div>))}</div></div>
      <div><H>Right now</H><div className="flex flex-wrap gap-2 mt-3">{r.seasonal.map(s=>(<div key={s.action} className="bg-amber-50 rounded-lg px-3 py-2 text-xs"><p className="font-medium text-amber-900">{s.action}</p><p className="text-amber-700 mt-0.5">{s.timing}</p></div>))}</div></div>
      <div><H>Rebates worth checking</H><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-3">{r.programs.map(p=>(<div key={p.name} className="bg-stone-50 rounded-xl p-3"><p className="text-xs font-semibold text-stone-800">{p.name}</p><p className="text-xs text-emerald-600 mt-1">{p.value}</p><p className="text-[10px] text-stone-400 mt-0.5">{p.caveat.split('.')[0]}.</p>{p.url&&<a href={p.url} target="_blank" rel="noopener noreferrer" className="text-[10px] text-sky-500 hover:underline mt-1 inline-block">Details &rarr;</a>}</div>))}</div></div>
      <div><H>Verify this yourself</H><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-3">{r.dataLinks.map(dl=>(<a key={dl.label} href={dl.url} target="_blank" rel="noopener noreferrer" className="bg-stone-50 rounded-xl p-3 hover:bg-stone-100 transition-colors block"><p className="text-xs font-semibold text-stone-800">{dl.label} <span className="text-sky-500">&rarr;</span></p><p className="text-[10px] text-stone-400 mt-0.5">{dl.what.split('.')[0]}.</p></a>))}</div></div>
      <div className="pt-6 border-t border-stone-100 text-[10px] text-stone-300">Not legal, tax, or engineering advice. Data from VT E911 geocoder, FEMA NFHL, ANR shoreland/wetland/river corridor layers, and Efficiency Vermont.</div>
    </div>)}
    {!r&&!loading&&!err&&(<div className="text-center py-20 text-sm text-stone-300">Enter an address or pick a town above.</div>)}
  </main></div>)
}
function H({children}:{children:string}){return<h2 className="text-xs font-semibold text-stone-400 uppercase tracking-widest">{children}</h2>}
